.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/arm_kinematics.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/arm_kinematics.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <tf_conversions/tf_kdl\&.h>\fP
.br
\fC#include <tf/transform_datatypes\&.h>\fP
.br
\fC#include <kdl_parser/kdl_parser\&.hpp>\fP
.br
\fC#include <kdl/jntarray\&.hpp>\fP
.br
\fC#include <kdl/chainiksolverpos_nr_jl\&.hpp>\fP
.br
\fC#include <kdl/chainiksolvervel_pinv\&.hpp>\fP
.br
\fC#include <kdl/chainfksolverpos_recursive\&.hpp>\fP
.br
\fC#include <moveit_msgs/GetPositionFK\&.h>\fP
.br
\fC#include <moveit_msgs/GetPositionIK\&.h>\fP
.br
\fC#include <moveit_msgs/GetKinematicSolverInfo\&.h>\fP
.br
\fC#include <moveit_msgs/KinematicSolverInfo\&.h>\fP
.br
\fC#include <urdf/model\&.h>\fP
.br
\fC#include 'nist_fanuc/Globals\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKinematics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
