.TH "Checkers::BoardType" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checkers::BoardType \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Checkers\&.h>\fP
.PP
Inherits vector< std::vector< int > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoardType\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Checkers::BoardType::BoardType ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
