.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Checkerboard.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Checkerboard.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rviz_visual_tools/rviz_visual_tools\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <geometry_msgs/PointStamped\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/thread/mutex\&.hpp>\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Scene\&.h'\fP
.br
\fC#include 'Checkers\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br
\fC#include 'Demo\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRvizCheckers\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUPDOWN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UPDOWN"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
