.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Conversions.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Conversions.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Eigen/Core>\fP
.br
\fC#include <Eigen/Geometry>\fP
.br
\fC#include 'geometry_msgs/PointStamped\&.h'\fP
.br
\fC#include 'geometry_msgs/Point32\&.h'\fP
.br
\fC#include 'geometry_msgs/PoseStamped\&.h'\fP
.br
\fC#include <tf_conversions/tf_eigen\&.h>\fP
.br
\fC#include <eigen_conversions/eigen_msg\&.h>\fP
.br
\fC#include 'RCS\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBConversion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > tf::Vector3 \fBConversion::vectorEigenToTF\fP (T e)"
.br
.ti -1c
.RI "template<typename T > tf::Vector3 \fBConversion::matrixEigenToTfVector\fP (T e)"
.br
.ti -1c
.RI "tf::Pose \fBConversion::Identity\fP ()"
.br
.ti -1c
.RI "tf::Pose \fBConversion::Affine3d2RcsPose\fP (const Eigen::Affine3d &pose)"
.br
.RI "\fIaffine3d2RcsPose converts an Eigen affine 4x4 matrix o represent the pose into a urdf pose vparam pose eigen Affine3d pose \fP"
.ti -1c
.RI "tf::Pose & \fBConversion::GeometryPose2TfPose\fP (const geometry_msgs::Pose &m, tf::Pose &p)"
.br
.ti -1c
.RI "tf::Quaternion \fBConversion::quaternionEigenToTF\fP (const Eigen::Quaterniond &e)"
.br
.ti -1c
.RI "tf::Pose \fBConversion::GeomMsgPose2RcsPose\fP (const geometry_msgs::Pose &m)"
.br
.ti -1c
.RI "tf::Quaternion \fBConversion::RPYRadians\fP (double roll, double pitch, double yaw)"
.br
.ti -1c
.RI "tf::Quaternion \fBConversion::RPYDegrees\fP (double roll, double pitch, double yaw)"
.br
.ti -1c
.RI "geometry_msgs::Pose \fBConversion::convertPointToPose\fP (const geometry_msgs::Point &point)"
.br
.ti -1c
.RI "geometry_msgs::Point \fBConversion::convertPoint\fP (const geometry_msgs::Vector3 &point)"
.br
.ti -1c
.RI "geometry_msgs::Pose \fBConversion::convertPose\fP (const Eigen::Affine3d &pose)"
.br
.ti -1c
.RI "geometry_msgs::Point \fBConversion::convertPoseToPoint\fP (const Eigen::Affine3d &pose)"
.br
.ti -1c
.RI "geometry_msgs::Point32 \fBConversion::convertPoint32\fP (const Eigen::Vector3d &point)"
.br
.ti -1c
.RI "geometry_msgs::Point \fBConversion::convertPoint\fP (const Eigen::Vector3d &point)"
.br
.ti -1c
.RI "geometry_msgs::Pose \fBConversion::PoseAffineToGeomMsg\fP (const Eigen::Affine3d &e)"
.br
.ti -1c
.RI "geometry_msgs::Pose \fBConversion::RcsPose2GeomMsgPose\fP (const tf::Pose &m)"
.br
.ti -1c
.RI "geometry_msgs::Pose & \fBConversion::TfPose2GeometryPose\fP (tf::Pose &m, geometry_msgs::Pose &p)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::GeomMsgPose2Affine3d\fP (const geometry_msgs::Pose &m)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::convertPose\fP (const geometry_msgs::Pose &pose)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::convertPoint32ToPose\fP (const geometry_msgs::Point32 &point)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::convertPointToPose\fP (const Eigen::Vector3d &point)"
.br
.ti -1c
.RI "Eigen::Vector3d \fBConversion::convertPoint\fP (const geometry_msgs::Point &point)"
.br
.ti -1c
.RI "Eigen::Vector3d \fBConversion::convertPoint32\fP (const geometry_msgs::Point32 &point)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::RcsPose2Affine3d\fP (const tf::Pose &pose)"
.br
.RI "\fIurdfPose2Affine3d converts urdf pose into an Eigen affine 4x4 matrix o represent the pose \fP"
.ti -1c
.RI "Eigen::Translation3d \fBConversion::RcsPose2EigenPosition\fP (const geometry_msgs::Pose &pose)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBConversion::EigenPosition2EigenAffine3d\fP (const Eigen::Translation3d &trans)"
.br
.ti -1c
.RI "Eigen::Vector3d \fBConversion::vectorTFToEigen\fP (tf::Vector3 t)"
.br
.ti -1c
.RI "\fBJointState\fP \fBConversion::JntPosVector2JointState\fP (const std::vector< double > &src)"
.br
.ti -1c
.RI "std::vector< geometry_msgs::Pose > \fBConversion::RcsPoses2PoseMsgs\fP (const std::vector< tf::Pose > &src)"
.br
.ti -1c
.RI "std::vector< tf::Pose > \fBConversion::PoseMsgs2RcsPoses\fP (const std::vector< geometry_msgs::Pose > &src)"
.br
.ti -1c
.RI "std::vector< Eigen::Affine3d > \fBConversion::PoseMsgs2AffEigenPoses\fP (const std::vector< geometry_msgs::Pose > &src)"
.br
.ti -1c
.RI "std::vector< geometry_msgs::Pose > \fBConversion::AffEigenPoses2PoseMsgs\fP (const std::vector< Eigen::Affine3d > &src)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
