.TH "ikfast::IkSolutionBase< T >" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ikfast::IkSolutionBase< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ikfast\&.h>\fP
.PP
Inherited by \fBikfast::IkSolution< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IkSolutionBase\fP ()"
.br
.ti -1c
.RI "virtual void \fBGetSolution\fP (T *solution, const T *freevalues) const =0"
.br
.ti -1c
.RI "virtual void \fBGetSolution\fP (std::vector< T > &solution, const std::vector< T > &freevalues) const "
.br
.ti -1c
.RI "virtual const std::vector< int > & \fBGetFree\fP () const =0"
.br
.ti -1c
.RI "virtual const int \fBGetDOF\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> virtual \fBikfast::IkSolutionBase\fP< T >::~\fBIkSolutionBase\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual const int \fBikfast::IkSolutionBase\fP< T >::GetDOF () const\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolution< T >\fP\&.
.SS "template<typename T> virtual const std::vector<int>& \fBikfast::IkSolutionBase\fP< T >::GetFree () const\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolution< T >\fP\&.
.SS "template<typename T> virtual void \fBikfast::IkSolutionBase\fP< T >::GetSolution (T *solution, const T *freevalues) const\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolution< T >\fP\&.
.SS "template<typename T> virtual void \fBikfast::IkSolutionBase\fP< T >::GetSolution (std::vector< T > &solution, const std::vector< T > &freevalues) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBikfast::IkSolution< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
