.TH "ikfast::IkSolutionListBase< T >" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ikfast::IkSolutionListBase< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ikfast\&.h>\fP
.PP
Inherited by \fBikfast::IkSolutionList< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IkSolutionListBase\fP ()"
.br
.ti -1c
.RI "virtual size_t \fBAddSolution\fP (const std::vector< \fBIkSingleDOFSolutionBase\fP< T > > &vinfos, const std::vector< int > &vfree)=0"
.br
.ti -1c
.RI "virtual const \fBIkSolutionBase\fP< T > & \fBGetSolution\fP (size_t index) const =0"
.br
.ti -1c
.RI "virtual size_t \fBGetNumSolutions\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBClear\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> virtual \fBikfast::IkSolutionListBase\fP< T >::~\fBIkSolutionListBase\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual size_t \fBikfast::IkSolutionListBase\fP< T >::AddSolution (const std::vector< \fBIkSingleDOFSolutionBase\fP< T > > &vinfos, const std::vector< int > &vfree)\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolutionList< T >\fP\&.
.SS "template<typename T> virtual void \fBikfast::IkSolutionListBase\fP< T >::Clear ()\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolutionList< T >\fP\&.
.SS "template<typename T> virtual size_t \fBikfast::IkSolutionListBase\fP< T >::GetNumSolutions () const\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolutionList< T >\fP\&.
.SS "template<typename T> virtual const \fBIkSolutionBase\fP<T>& \fBikfast::IkSolutionListBase\fP< T >::GetSolution (size_tindex) const\fC [pure virtual]\fP"

.PP
Implemented in \fBikfast::IkSolutionList< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
