.TH "ikfast::IkSingleDOFSolutionBase< T >" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ikfast::IkSingleDOFSolutionBase< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ikfast\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIkSingleDOFSolutionBase\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBfmul\fP"
.br
.ti -1c
.RI "T \fBfoffset\fP"
.br
.ti -1c
.RI "signed char \fBfreeind\fP"
.br
.ti -1c
.RI "unsigned char \fBjointtype\fP"
.br
.ti -1c
.RI "unsigned char \fBmaxsolutions\fP"
.br
.ti -1c
.RI "unsigned char \fBindices\fP [5]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBikfast::IkSingleDOFSolutionBase\fP< T >::\fBIkSingleDOFSolutionBase\fP ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > T \fBikfast::IkSingleDOFSolutionBase\fP< T >::fmul"

.SS "template<typename T > T \fBikfast::IkSingleDOFSolutionBase\fP< T >::foffset"

.SS "template<typename T > signed char \fBikfast::IkSingleDOFSolutionBase\fP< T >::freeind"

.SS "template<typename T > unsigned char \fBikfast::IkSingleDOFSolutionBase\fP< T >::indices[5]"

.SS "template<typename T > unsigned char \fBikfast::IkSingleDOFSolutionBase\fP< T >::jointtype"

.SS "template<typename T > unsigned char \fBikfast::IkSingleDOFSolutionBase\fP< T >::maxsolutions"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
