.TH "InlineRobotCommands" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InlineRobotCommands \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Demo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInlineRobotCommands\fP (boost::shared_ptr< \fBRCS::CController\fP > \fBcnc\fP, \fBNearestJointsLookup\fP &hints)"
.br
.ti -1c
.RI "boost::shared_ptr
.br
< \fBRCS::CController\fP > \fBcnc\fP ()"
.br
.ti -1c
.RI "void \fBPick\fP (\fBRCS::Pose\fP pose, std::string objname)"
.br
.ti -1c
.RI "void \fBMoveTo\fP (\fBRCS::Pose\fP pose, std::string objname='')"
.br
.ti -1c
.RI "void \fBDoDwell\fP (double dwelltime)"
.br
.ti -1c
.RI "void \fBAddGripperOffset\fP ()"
.br
.ti -1c
.RI "void \fBOpenGripper\fP ()"
.br
.ti -1c
.RI "void \fBCloseGripper\fP ()"
.br
.ti -1c
.RI "void \fBSetGripper\fP (double ee)"
.br
.ti -1c
.RI "void \fBPlace\fP (\fBRCS::Pose\fP pose, std::string objname)"
.br
.ti -1c
.RI "void \fBMoveObject\fP (std::string objname, \fBRCS::Pose\fP pose, int color)"
.br
.ti -1c
.RI "void \fBEraseObject\fP (std::string objname)"
.br
.ti -1c
.RI "void \fBTestRobotCommands\fP ()"
.br
.ti -1c
.RI "void \fBMoveJoints\fP (std::vector< long unsigned int > jointnum, std::vector< double > positions)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmydwell\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr
.br
< \fBRCS::CController\fP > \fB_cnc\fP"
.br
.ti -1c
.RI "\fBNearestJointsLookup\fP & \fB_hints\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fBcrclcommandnum\fP = 1"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InlineRobotCommands::InlineRobotCommands (boost::shared_ptr< \fBRCS::CController\fP >cnc, \fBNearestJointsLookup\fP &hints)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void InlineRobotCommands::AddGripperOffset ()"

.SS "void InlineRobotCommands::CloseGripper ()"

.SS "boost::shared_ptr<\fBRCS::CController\fP> InlineRobotCommands::cnc ()\fC [inline]\fP"

.SS "void InlineRobotCommands::DoDwell (doubledwelltime)"

.SS "void InlineRobotCommands::EraseObject (std::stringobjname)"

.SS "void InlineRobotCommands::MoveJoints (std::vector< long unsigned int >jointnum, std::vector< double >positions)"

.SS "void InlineRobotCommands::MoveObject (std::stringobjname, \fBRCS::Pose\fPpose, intcolor)"

.SS "void InlineRobotCommands::MoveTo (\fBRCS::Pose\fPpose, std::stringobjname = \fC''\fP)"

.SS "void InlineRobotCommands::OpenGripper ()"

.SS "void InlineRobotCommands::Pick (\fBRCS::Pose\fPpose, std::stringobjname)"

.SS "void InlineRobotCommands::Place (\fBRCS::Pose\fPpose, std::stringobjname)"

.SS "void InlineRobotCommands::SetGripper (doubleee)"

.SS "void InlineRobotCommands::TestRobotCommands ()"

.SH "Member Data Documentation"
.PP 
.SS "boost::shared_ptr<\fBRCS::CController\fP> InlineRobotCommands::_cnc\fC [protected]\fP"

.SS "\fBNearestJointsLookup\fP& InlineRobotCommands::_hints\fC [protected]\fP"

.SS "int InlineRobotCommands::crclcommandnum = 1\fC [static]\fP, \fC [protected]\fP"

.SS "double InlineRobotCommands::mydwell"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
