.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/src/RCS.cpp" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/src/RCS.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RCS\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br
\fC#include 'Debug\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBRCS::getRPY\fP (const \fBRCS::Pose\fP pose, double &roll, double &pitch, double &yaw)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
