.TH "RCS::CsvLogging" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CsvLogging \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CsvLogging\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCsvLogging\fP ()"
.br
.ti -1c
.RI "\fB~CsvLogging\fP ()"
.br
.ti -1c
.RI "void \fBOpen\fP (std::string filepath)"
.br
.ti -1c
.RI "std::string \fBDumpHeader\fP (std::string separator, size_t jointnum)"
.br
.ti -1c
.RI "std::string \fBDump\fP (std::string separator, \fBCanonWorldModel\fP &)"
.br
.ti -1c
.RI "void \fBMotionLogging\fP (\fBCanonWorldModel\fP &status)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RCS::CsvLogging::CsvLogging ()\fC [inline]\fP"

.SS "RCS::CsvLogging::~CsvLogging ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string RCS::CsvLogging::Dump (std::stringseparator, \fBCanonWorldModel\fP &status)"
< copy of current command type
.PP
< copy of current status type 
.SS "std::string RCS::CsvLogging::DumpHeader (std::stringseparator, size_tjointnum)"

.SS "void RCS::CsvLogging::MotionLogging (\fBCanonWorldModel\fP &status)"

.SS "void RCS::CsvLogging::Open (std::stringfilepath)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
