.TH "RCS::CanonAngleUnit" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonAngleUnit \- 
.PP
enumeration of angle units\&. \fBConversion\fP into ROS compatible radians\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBRADIAN\fP = 0"
.br
.ti -1c
.RI "static const int \fBDEGREE\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of angle units\&. \fBConversion\fP into ROS compatible radians\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonAngleUnit::DEGREE = 1\fC [static]\fP"

.SS "const int RCS::CanonAngleUnit::RADIAN = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
