.TH "RCS::CanonAccProfile" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonAccProfile \- 
.PP
enumeration of trajectory acceleration profile\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBMS_IS_UNSET\fP = 0"
.br
.ti -1c
.RI "static const int \fBMS_IS_DONE\fP = 1"
.br
.ti -1c
.RI "static const int \fBMS_IS_ACCEL\fP = 2"
.br
.ti -1c
.RI "static const int \fBMS_IS_CONST\fP = 3"
.br
.ti -1c
.RI "static const int \fBMS_IS_DECEL\fP = 4"
.br
.ti -1c
.RI "static const int \fBMS_IS_ESTOPPING\fP = 5"
.br
.ti -1c
.RI "static const int \fBMS_IS_PAUSED\fP = 6"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of trajectory acceleration profile\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonAccProfile::MS_IS_ACCEL = 2\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_CONST = 3\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_DECEL = 4\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_DONE = 1\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_ESTOPPING = 5\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_PAUSED = 6\fC [static]\fP"

.SS "const int RCS::CanonAccProfile::MS_IS_UNSET = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
