.TH "RCS::MovementType" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::MovementType \- 
.PP
enumeration of trajectory motion type, joint or cartesian\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBMOVE_DEFAULT\fP = 0"
.br
.ti -1c
.RI "static const int \fBMOVE_CARTESIAN\fP = 1"
.br
.ti -1c
.RI "static const int \fBMOVE_JOINT\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of trajectory motion type, joint or cartesian\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::MovementType::MOVE_CARTESIAN = 1\fC [static]\fP"

.SS "const int RCS::MovementType::MOVE_DEFAULT = 0\fC [static]\fP"

.SS "const int RCS::MovementType::MOVE_JOINT = 2\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
