.TH "RCS::CanonTorqueUnit" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonTorqueUnit \- 
.PP
enumeration of torque units\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBNEWTONMETER\fP = 0"
.br
.ti -1c
.RI "static const int \fBFOOTPOUND\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of torque units\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonTorqueUnit::FOOTPOUND = 2\fC [static]\fP"

.SS "const int RCS::CanonTorqueUnit::NEWTONMETER = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
