.TH "RCS::CanonStatusType" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonStatusType \- 
.PP
enumeration of controller status types for individual commands\&. Note, even though command types are listed, not all used or supported\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCANON_DONE\fP = 0"
.br
.ti -1c
.RI "static const int \fBCANON_ERROR\fP = 2"
.br
.ti -1c
.RI "static const int \fBCANON_WORKING\fP = 3"
.br
.ti -1c
.RI "static const int \fBCANON_PAUSED\fP = 2"
.br
.ti -1c
.RI "static const int \fBCANON_ABORT\fP = 4"
.br
.ti -1c
.RI "static const int \fBCANON_WAITING\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of controller status types for individual commands\&. Note, even though command types are listed, not all used or supported\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonStatusType::CANON_ABORT = 4\fC [static]\fP"

.SS "const int RCS::CanonStatusType::CANON_DONE = 0\fC [static]\fP"
uint8 done=0 uint8 error=1 uint8 working=2 
.SS "const int RCS::CanonStatusType::CANON_ERROR = 2\fC [static]\fP"

.SS "const int RCS::CanonStatusType::CANON_PAUSED = 2\fC [static]\fP"

.SS "const int RCS::CanonStatusType::CANON_WAITING = 5\fC [static]\fP"

.SS "const int RCS::CanonStatusType::CANON_WORKING = 3\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
