.TH "RCS::IRCSInterpreter" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::IRCSInterpreter \- 
.PP
IInterpreter parses a \fBRCS\fP command and generates robot motion commands\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.PP
Inherited by \fBRCS::BangBangInterpreter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBRCS::CanonCmd\fP \fBParseCommand\fP (\fBRCS::CanonCmd\fP cmd)=0"
.br
.ti -1c
.RI "virtual void \fBSetRange\fP (std::vector< double > minrange, std::vector< double > maxrange)"
.br
.in -1c
.SH "Detailed Description"
.PP 
IInterpreter parses a \fBRCS\fP command and generates robot motion commands\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBRCS::CanonCmd\fP RCS::IRCSInterpreter::ParseCommand (\fBRCS::CanonCmd\fPcmd)\fC [pure virtual]\fP"

.PP
Implemented in \fBRCS::BangBangInterpreter\fP\&.
.SS "virtual void RCS::IRCSInterpreter::SetRange (std::vector< double >minrange, std::vector< double >maxrange)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBRCS::BangBangInterpreter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
