.TH "three21_kin" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
three21_kin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fanuc_lrmate200id\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBa1\fP"
.br
.ti -1c
.RI "double \fBa2\fP"
.br
.ti -1c
.RI "double \fBa3\fP"
.br
.ti -1c
.RI "double \fBd2\fP"
.br
.ti -1c
.RI "double \fBd3\fP"
.br
.ti -1c
.RI "double \fBd4\fP"
.br
.ti -1c
.RI "long \fBiflags\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double three21_kin::a1"

.SS "double three21_kin::a2"

.SS "double three21_kin::a3"

.SS "double three21_kin::d2"

.SS "double three21_kin::d3"

.SS "double three21_kin::d4"

.SS "long three21_kin::iflags"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
