gomotion: gomotion::go_motion_queue Struct Reference
gomotion::go_motion_queue Struct Reference
#include <gomotion.h>
Public Member Functions
go_result init (go_motion_spec *space, go_integer size, go_real deltat)
go_result reset ()
go_result set_type (go_flag type)
go_flag get_type ()
go_result set_joint_number (go_integer joints)
go_integer get_joint_number ()
go_result set_here (const go_position *here)
go_result set_cycle_time (go_real deltat)
go_result set_scale (go_real scale, go_real scale_v, go_real scale_a)
go_result append (const go_motion_spec *motion)
go_result number (go_integer *number)
go_result size (go_integer *size)
go_result head (go_motion_spec *motion)
go_result here (go_position *position)
go_result there (go_position *position)
go_result interp (go_position *position)
go_result stop (go_motion_queue *queue)
go_result set_id (go_integer id)
go_integer last_id ()
go_flag is_empty ()
go_result erase ()
go_result drop_pending ()
go_result stop ()
Data Fields
go_flag _type
go_MOTION_JOINT for joint, otherwise world
go_position _here
initial starting point
go_position _there
where the end is
go_motion_spec * _startptr
ptr to original start
go_motion_spec * _endptr
the original end
go_motion_spec * _start
ptr to first entry of the queue
go_motion_spec * _end
ptr to last (empty) entry
go_integer _size
size of whole queue
go_integer _joint_num
number of joints to be interpolated
go_integer _number
number of motions on queue
go_integer _last_id
id of last motion appended
go_real _deltat
cycle time
go_real _time
time into the current spec
go_scale_spec _timescale
walked-in time scale factor
Protected Member Functions
go_result append_joint (const go_motion_spec *motion)
go_result append_ujoint (const go_motion_spec *motion)
go_result append_world (const go_motion_spec *motion)
go_result interp_joint (go_real *joint)
go_result interp_world (go_pose *pose)
go_result interp_world (go_motion_spec *motion, go_real time, go_pose *pose)
Detailed Description
Definition at line 167 of file gomotion.h.
Member Function Documentation
go_result gomotion::go_motion_queue::append (const go_motion_spec * motion)
Definition at line 745 of file gomotion.cpp.
References _type, append_joint(), append_ujoint(), append_world(), gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, and GO_RESULT_ERROR.
go_result gomotion::go_motion_queue::append_joint (const go_motion_spec * motion) protected
Definition at line 378 of file gomotion.cpp.
References _end, _endptr, _joint_num, _last_id, _number, _size, _startptr, _there, gomotion::go_motion_params::acc, gomotion::go_motion_spec::cj, gomotion::go_motion_spec::end, GO_RESULT_NO_SPACE, GO_RESULT_OK, gomotion::go_traj_cj_compute(), gomotion::go_traj_cj_scale(), gomotion::go_motion_spec::id, gomotion::go_motion_params::jerk, gomotion::go_position::joint, gomotion::go_motion_spec::par, gomotion::go_motion_spec::start, gomotion::go_traj_cj_spec::tend, gomotion::go_motion_spec::totalt, gomotion::go_position::u, and gomotion::go_motion_params::vel.
Referenced by append().
go_result gomotion::go_motion_queue::append_ujoint (const go_motion_spec * motion) protected
Definition at line 436 of file gomotion.cpp.
References _end, _endptr, _joint_num, _last_id, _number, _size, _startptr, _there, gomotion::go_motion_params::acc, gomotion::go_motion_spec::cj, gomotion::go_motion_spec::end, GO_RESULT_NO_SPACE, GO_RESULT_OK, gomotion::go_traj_cj_compute(), gomotion::go_motion_spec::id, gomotion::go_motion_params::jerk, gomotion::go_position::joint, gomotion::go_motion_spec::par, gomotion::go_motion_spec::start, gomotion::go_traj_cj_spec::tend, gomotion::go_motion_spec::totalt, gomotion::go_position::u, and gomotion::go_motion_params::vel.
Referenced by append().
go_result gomotion::go_motion_queue::append_world (const go_motion_spec * motion) protected
Definition at line 580 of file gomotion.cpp.
References _end, _endptr, _last_id, _number, _size, _startptr, _there, gomotion::go_motion_params::acc, gomotion::go_motion_circular_params::center, gomotion::go_motion_spec::cj, gomotion::go_motion_spec::cpar, gomotion::go_motion_spec::end, GO_2_PI, gomotion::go_cart_cart_angle(), gomotion::go_cart_cart_cross(), gomotion::go_cart_cart_dot(), gomotion::go_cart_cart_sub(), gomotion::go_cart_mag(), gomotion::go_cart_plane_proj(), gomotion::go_cart_rvec_convert(), gomotion::go_cart_unit(), gomotion::GO_MOTION_CIRCULAR, gomotion::GO_MOTION_LINEAR, gomotion::go_quat_identity(), gomotion::go_quat_inv(), gomotion::go_quat_mag(), gomotion::go_quat_quat_mult(), gomotion::go_quat_unit(), GO_RESULT_ERROR, GO_RESULT_NO_SPACE, GO_RESULT_OK, gomotion::go_rvec_quat_convert(), go_sq, gomotion::go_traj_cj_compute(), gomotion::go_traj_cj_scale(), GO_TRAN_SMALL, gomotion::go_motion_spec::id, gomotion::go_motion_params::jerk, gomotion::go_motion_spec::lpar, gomotion::go_motion_circular_params::normal, gomotion::go_motion_spec::par, gomotion::go_position::pose, gomotion::go_motion_circular_params::qnormal, gomotion::go_pose::rot, gomotion::go_motion_circular_params::rstart, gomotion::go_motion_circular_params::rtot, gomotion::go_motion_spec::start, gomotion::go_motion_circular_params::stotinv, gomotion::go_traj_cj_spec::tend, gomotion::go_motion_circular_params::thtot, gomotion::go_motion_spec::totalt, gomotion::go_pose::tran, gomotion::go_motion_circular_params::turns, gomotion::go_motion_spec::type, gomotion::go_position::u, gomotion::go_motion_spec::u, gomotion::go_motion_spec::uquat, gomotion::go_motion_circular_params::urcsp, gomotion::go_motion_linear_params::uvec, gomotion::go_motion_params::vel, gomotion::go_cart::x, gomotion::go_cart::y, gomotion::go_cart::z, gomotion::go_motion_circular_params::zstart, and gomotion::go_motion_circular_params::ztot.
Referenced by append().
go_result gomotion::go_motion_queue::drop_pending ()
Definition at line 1105 of file gomotion.cpp.
References _end, _endptr, _number, _start, _startptr, and GO_RESULT_OK.
Referenced by stop().
go_result gomotion::go_motion_queue::erase ()
Definition at line 1081 of file gomotion.cpp.
References _endptr, _here, _number, _start, _startptr, _there, and GO_RESULT_OK.
Referenced by interp_joint(), and interp_world().
go_integer gomotion::go_motion_queue::get_joint_number ()
Definition at line 90 of file gomotion.cpp.
References _joint_num.
go_flag gomotion::go_motion_queue::get_type ()
Definition at line 220 of file gomotion.cpp.
References _type.
go_result gomotion::go_motion_queue::head (go_motion_spec * motion)
Definition at line 777 of file gomotion.cpp.
References _number, _start, GO_RESULT_EMPTY, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::here (go_position * position)
Definition at line 789 of file gomotion.cpp.
References _here, _joint_num, _type, gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_position::joint, gomotion::go_position::pose, and gomotion::go_position::u.
go_result gomotion::go_motion_queue::init (go_motion_spec * space, go_integer size, go_real deltat)
Definition at line 177 of file gomotion.cpp.
References _deltat, _endptr, _joint_num, _size, _startptr, GO_MOTION_JOINT_NUM, GO_RESULT_BAD_ARGS, reset(), and size().
go_result gomotion::go_motion_queue::interp (go_position * position)
Definition at line 949 of file gomotion.cpp.
References _deltat, _number, _time, _timescale, _type, gomotion::go_scale_spec::eval(), gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_ERROR, interp_joint(), interp_world(), gomotion::go_position::joint, gomotion::go_position::pose, gomotion::go_scale_spec::scale, and gomotion::go_position::u.
go_result gomotion::go_motion_queue::interp_joint (go_real * joint) protected
Definition at line 831 of file gomotion.cpp.
References _here, _joint_num, _number, _start, _time, gomotion::go_motion_spec::cj, gomotion::go_traj_interp_spec::d, gomotion::go_motion_spec::end, erase(), GO_RESULT_OK, gomotion::go_traj_cj_interp(), gomotion::go_position::joint, gomotion::go_motion_spec::start, gomotion::go_motion_spec::totalt, and gomotion::go_position::u.
Referenced by interp().
go_result gomotion::go_motion_queue::interp_world (go_pose * pose) protected
Definition at line 920 of file gomotion.cpp.
References _here, _number, _start, _there, _time, erase(), GO_RESULT_OK, gomotion::go_position::pose, gomotion::go_motion_spec::totalt, and gomotion::go_position::u.
Referenced by interp(), and stop().
go_result gomotion::go_motion_queue::interp_world (go_motion_spec * motion, go_real time, go_pose * pose) protected
Definition at line 867 of file gomotion.cpp.
References gomotion::go_motion_circular_params::center, gomotion::go_motion_spec::cj, gomotion::go_motion_spec::cpar, gomotion::go_traj_interp_spec::d, gomotion::go_motion_spec::end, gomotion::go_cart_cart_add(), gomotion::go_cart_scale_mult(), gomotion::GO_MOTION_CIRCULAR, gomotion::GO_MOTION_LINEAR, gomotion::go_quat_cart_mult(), gomotion::go_quat_quat_mult(), gomotion::go_quat_scale_mult(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_traj_cj_interp(), gomotion::go_motion_spec::lpar, gomotion::go_motion_circular_params::normal, gomotion::go_position::pose, gomotion::go_motion_circular_params::qnormal, gomotion::go_pose::rot, gomotion::go_motion_circular_params::rstart, gomotion::go_motion_circular_params::rtot, gomotion::go_motion_spec::start, gomotion::go_motion_circular_params::stotinv, gomotion::go_motion_circular_params::thtot, gomotion::go_pose::tran, gomotion::go_motion_spec::type, gomotion::go_position::u, gomotion::go_motion_spec::u, gomotion::go_motion_spec::uquat, gomotion::go_motion_circular_params::urcsp, gomotion::go_motion_linear_params::uvec, gomotion::go_motion_circular_params::zstart, and gomotion::go_motion_circular_params::ztot.
go_flag gomotion::go_motion_queue::is_empty ()
Definition at line 1076 of file gomotion.cpp.
References _number.
go_integer gomotion::go_motion_queue::last_id ()
Definition at line 1071 of file gomotion.cpp.
References _last_id.
go_result gomotion::go_motion_queue::number (go_integer * number)
Definition at line 763 of file gomotion.cpp.
References _number, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::reset ()
Definition at line 195 of file gomotion.cpp.
References _end, _last_id, _number, _start, _startptr, _time, _timescale, _type, gomotion::GO_MOTION_NONE, and gomotion::go_scale_spec::init().
Referenced by init().
go_result gomotion::go_motion_queue::set_cycle_time (go_real deltat)
Definition at line 250 of file gomotion.cpp.
References _deltat, GO_RESULT_BAD_ARGS, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::set_here (const go_position * here)
Definition at line 225 of file gomotion.cpp.
References _here, _joint_num, _number, _there, _type, gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_position::joint, gomotion::go_position::pose, and gomotion::go_position::u.
go_result gomotion::go_motion_queue::set_id (go_integer id)
Definition at line 1064 of file gomotion.cpp.
References _last_id, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::set_joint_number (go_integer joints)
Definition at line 78 of file gomotion.cpp.
References _joint_num, GO_MOTION_JOINT_NUM, GO_RESULT_BAD_ARGS, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::set_scale (go_real scale, go_real scale_v, go_real scale_a)
Definition at line 343 of file gomotion.cpp.
References _timescale, and gomotion::go_scale_spec::set().
go_result gomotion::go_motion_queue::set_type (go_flag type)
Definition at line 207 of file gomotion.cpp.
References _type, gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_NONE, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_ERROR, and GO_RESULT_OK.
go_result gomotion::go_motion_queue::size (go_integer * size)
Definition at line 770 of file gomotion.cpp.
References _size, and GO_RESULT_OK.
Referenced by init().
go_result gomotion::go_motion_queue::stop (go_motion_queue * queue)
go_result gomotion::go_motion_queue::stop ()
Definition at line 975 of file gomotion.cpp.
References _joint_num, _number, _start, _there, _time, _type, gomotion::go_motion_spec::cj, drop_pending(), gomotion::go_traj_cj_spec::dtend, gomotion::go_motion_spec::end, gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_BUG, GO_RESULT_OK, gomotion::go_traj_cj_extend(), gomotion::go_traj_cj_stop(), interp_world(), gomotion::go_position::joint, maxit, gomotion::go_position::pose, gomotion::go_motion_spec::start, gomotion::go_traj_cj_spec::tend, gomotion::go_motion_spec::totalt, and gomotion::go_position::u.
go_result gomotion::go_motion_queue::there (go_position * position)
Definition at line 810 of file gomotion.cpp.
References _joint_num, _there, _type, gomotion::GO_MOTION_JOINT, gomotion::GO_MOTION_UJOINT, gomotion::GO_MOTION_WORLD, GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_position::joint, gomotion::go_position::pose, and gomotion::go_position::u.
Field Documentation
go_real gomotion::go_motion_queue::_deltat
cycle time
Definition at line 179 of file gomotion.h.
Referenced by init(), interp(), and set_cycle_time().
go_motion_spec* gomotion::go_motion_queue::_end
ptr to last (empty) entry
Definition at line 174 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), drop_pending(), and reset().
go_motion_spec* gomotion::go_motion_queue::_endptr
the original end
Definition at line 172 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), drop_pending(), erase(), and init().
go_position gomotion::go_motion_queue::_here
initial starting point
Definition at line 169 of file gomotion.h.
Referenced by erase(), here(), interp_joint(), interp_world(), and set_here().
go_integer gomotion::go_motion_queue::_joint_num
number of joints to be interpolated
Definition at line 176 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), get_joint_number(), here(), init(), interp_joint(), set_here(), set_joint_number(), stop(), and there().
go_integer gomotion::go_motion_queue::_last_id
id of last motion appended
Definition at line 178 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), last_id(), reset(), and set_id().
go_integer gomotion::go_motion_queue::_number
number of motions on queue
Definition at line 177 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), drop_pending(), erase(), head(), interp(), interp_joint(), interp_world(), is_empty(), number(), reset(), set_here(), and stop().
go_integer gomotion::go_motion_queue::_size
size of whole queue
Definition at line 175 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), init(), and size().
go_motion_spec* gomotion::go_motion_queue::_start
ptr to first entry of the queue
Definition at line 173 of file gomotion.h.
Referenced by drop_pending(), erase(), head(), interp_joint(), interp_world(), reset(), and stop().
go_motion_spec* gomotion::go_motion_queue::_startptr
ptr to original start
Definition at line 171 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), drop_pending(), erase(), init(), and reset().
go_position gomotion::go_motion_queue::_there
where the end is
Definition at line 170 of file gomotion.h.
Referenced by append_joint(), append_ujoint(), append_world(), erase(), interp_world(), set_here(), stop(), and there().
go_real gomotion::go_motion_queue::_time
time into the current spec
Definition at line 180 of file gomotion.h.
Referenced by interp(), interp_joint(), interp_world(), reset(), and stop().
go_scale_spec gomotion::go_motion_queue::_timescale
walked-in time scale factor
Definition at line 181 of file gomotion.h.
Referenced by interp(), reset(), and set_scale().
go_flag gomotion::go_motion_queue::_type
go_MOTION_JOINT for joint, otherwise world
Definition at line 168 of file gomotion.h.
Referenced by append(), get_type(), here(), interp(), reset(), set_here(), set_type(), stop(), and there().
The documentation for this struct was generated from the following files:
/usr/local/michalos/nistfanuc_ws/src/gomotion/include/gomotion/gomotion.h
/usr/local/michalos/nistfanuc_ws/src/gomotion/src/gomotion.cpp