gomotion: gomotion Namespace Reference
gomotion Namespace Reference
Data Structures
struct go_motion_interface
struct points
This structure holds the points to be interpolated.
struct coeff
This structure holds the polynomial coefficients.
class go_interp
The interpolator structure.
struct go_cart
struct go_sph
struct go_cyl
struct go_rvec
struct go_mat
struct go_quat
struct go_zyz
struct go_zyx
struct go_xyz
struct go_rpy
struct go_uxz
struct go_pose
struct go_vel
struct go_hom
struct go_line
struct go_plane
struct go_matrix
struct go_dh
struct go_pk
struct go_pp
struct go_body
struct go_link
struct go_complex
struct go_quadratic
struct go_cubic
struct go_quartic
struct go_position
Depending upon whether you are doing joint interpolation or world coordinate interpolation (as specified by your call to go_motion_queue_set_type()), fill in joint[] or pose accordingly.
struct go_motion_params
struct go_motion_linear_params
In the following comments, LIN, CIR and ALL refer to linear moves, circular moves and both, respectively.
struct go_motion_circular_params
struct go_motion_spec
struct go_scale_spec
struct go_motion_queue
struct GoMotionParams
class GoMotion
struct go_traj_ca_spec
struct go_traj_cj_spec
struct go_traj_interp_spec
Typedefs
typedef go_real go_vector
typedef
sensor_msgs::JointState_
< std::allocator< void > > JointState
Enumerations
enum { COEFF_MAX = 6 }
How many coefficients we support, one more than max polynomial degree.
enum { GO_LINK_DH = 1, GO_LINK_PK, GO_LINK_PP }
enum {
GO_MOTION_NONE, GO_MOTION_JOINT, GO_MOTION_UJOINT, GO_MOTION_WORLD,
GO_MOTION_LINEAR, GO_MOTION_CIRCULAR
}
Functions
void sincos (double x, double *sx, double *cx)
void go_sincos (go_real t, go_real *s, go_real *c)
go_result go_asines (go_real s, go_real *asp, go_real *asn)
go_result go_acoses (go_real c, go_real *acp, go_real *acn)
go_result go_atans (go_real t, go_real *atp, go_real *atn)
go_real go_cbrt (go_real x)
go_result go_cart_sph_convert (const go_cart *v, go_sph *s)
go_result go_cart_cyl_convert (const go_cart *v, go_cyl *c)
go_result go_sph_cart_convert (const go_sph *s, go_cart *v)
go_result go_sph_cyl_convert (const go_sph *s, go_cyl *c)
go_result go_cyl_cart_convert (const go_cyl *c, go_cart *v)
go_result go_cyl_sph_convert (const go_cyl *c, go_sph *s)
go_result go_rvec_quat_convert (const go_rvec *r, go_quat *q)
go_result go_rvec_mat_convert (const go_rvec *r, go_mat *m)
go_result go_rvec_zyz_convert (const go_rvec *rvec, go_zyz *zyz)
go_result go_rvec_zyx_convert (const go_rvec *rvec, go_zyx *zyx)
go_result go_rvec_rpy_convert (const go_rvec *r, go_rpy *rpy)
go_result go_quat_rvec_convert (const go_quat *q, go_rvec *r)
go_result go_quat_mat_convert (const go_quat *q, go_mat *m)
go_result go_quat_zyz_convert (const go_quat *q, go_zyz *zyz)
go_result go_quat_zyx_convert (const go_quat *q, go_zyx *zyx)
go_result go_quat_rpy_convert (const go_quat *q, go_rpy *rpy)
go_result go_mat_rvec_convert (const go_mat *m, go_rvec *r)
go_result go_mat_quat_convert (const go_mat *m, go_quat *q)
go_result go_mat_zyz_convert (const go_mat *m, go_zyz *zyz)
go_result go_mat_zyx_convert (const go_mat *m, go_zyx *zyx)
go_result go_mat_xyz_convert (const go_mat *m, go_xyz *xyz)
go_result go_mat_rpy_convert (const go_mat *m, go_rpy *rpy)
go_result go_zyz_rvec_convert (const go_zyz *zyz, go_rvec *r)
go_result go_zyz_quat_convert (const go_zyz *zyz, go_quat *q)
go_result go_zyz_mat_convert (const go_zyz *zyz, go_mat *m)
go_result go_zyz_zyx_convert (const go_zyz *zyz, go_zyx *zyx)
go_result go_zyz_rpy_convert (const go_zyz *zyz, go_rpy *rpy)
go_result go_zyx_rvec_convert (const go_zyx *zyx, go_rvec *r)
go_result go_zyx_quat_convert (const go_zyx *zyx, go_quat *q)
go_result go_zyx_mat_convert (const go_zyx *zyx, go_mat *m)
go_result go_zyx_zyz_convert (const go_zyx *zyx, go_zyz *zyz)
go_result go_zyx_rpy_convert (const go_zyx *zyx, go_rpy *rpy)
go_result go_xyz_mat_convert (const go_xyz *xyz, go_mat *m)
go_result go_rpy_rvec_convert (const go_rpy *rpy, go_rvec *rvec)
go_result go_rpy_quat_convert (const go_rpy *rpy, go_quat *quat)
go_result go_rpy_mat_convert (const go_rpy *rpy, go_mat *m)
go_result go_rpy_zyz_convert (const go_rpy *rpy, go_zyz *zyz)
go_result go_rpy_zyx_convert (const go_rpy *rpy, go_zyx *zyx)
go_result go_uxz_mat_convert (const go_uxz *uxz, go_mat *mat)
go_result go_mat_uxz_convert (const go_mat *mat, go_uxz *uxz)
go_pose go_pose_this (go_real x, go_real y, go_real z, go_real rs, go_real rx, go_real ry, go_real rz)
go_cart go_cart_zero (void)
go_quat go_quat_identity (void)
go_pose go_pose_identity (void)
go_result go_pose_hom_convert (const go_pose *p, go_hom *h)
go_result go_hom_pose_convert (const go_hom *h, go_pose *p)
go_result go_cart_rvec_convert (const go_cart *cart, go_rvec *rvec)
go_result go_rvec_cart_convert (const go_rvec *rvec, go_cart *cart)
go_flag go_cart_cart_compare (const go_cart *v1, const go_cart *v2)
go_result go_cart_cart_dot (const go_cart *v1, const go_cart *v2, go_real *d)
go_result go_cart_cart_cross (const go_cart *v1, const go_cart *v2, go_cart *vout)
go_result go_cart_mag (const go_cart *v, go_real *d)
go_result go_cart_magsq (const go_cart *v, go_real *d)
go_flag go_cart_cart_par (const go_cart *v1, const go_cart *v2)
go_flag go_cart_cart_perp (const go_cart *v1, const go_cart *v2)
go_result go_cart_cart_disp (const go_cart *v1, const go_cart *v2, go_real *d)
go_result go_cart_cart_add (const go_cart *v1, const go_cart *v2, go_cart *vout)
go_result go_cart_cart_sub (const go_cart *v1, const go_cart *v2, go_cart *vout)
go_result go_cart_scale_mult (const go_cart *v1, go_real d, go_cart *vout)
go_result go_cart_neg (const go_cart *v1, go_cart *vout)
go_result go_cart_unit (const go_cart *v, go_cart *vout)
go_result go_cart_is_norm (const go_cart *v)
go_result go_cart_cart_rot (const go_cart *v1, const go_cart *v2, go_quat *quat)
go_result go_cart_cart_proj (const go_cart *v1, const go_cart *v2, go_cart *vout)
go_result go_cart_plane_proj (const go_cart *v, const go_cart *normal, go_cart *vout)
go_result go_cart_cart_angle (const go_cart *v1, const go_cart *v2, go_real *a)
go_result go_cart_normal (const go_cart *v, go_cart *vout)
go_result go_cart_centroid (const go_cart *varray, go_integer num, go_cart *centroid)
go_result go_cart_centroidize (const go_cart *vinarray, go_integer num, go_cart *centroid, go_cart *voutarray)
go_complex go_complex_add (go_complex z1, go_complex z2)
go_complex go_complex_sub (go_complex z1, go_complex z2)
go_complex go_complex_mult (go_complex z1, go_complex z2)
go_complex go_complex_inv (go_complex z, go_result *result)
go_complex go_complex_div (go_complex z1, go_complex z2, go_result *result)
go_complex go_complex_sq (go_complex z)
go_complex go_complex_scale (go_complex z, go_real scale)
go_real go_complex_mag (go_complex z)
go_real go_complex_magsq (go_complex z)
go_real go_complex_arg (go_complex z)
void go_complex_sqrt (go_complex z, go_complex *z1, go_complex *z2)
void go_complex_cbrt (go_complex z, go_complex *z1, go_complex *z2, go_complex *z3)
go_result go_quadratic_solve (const go_quadratic *quad, go_complex *z1, go_complex *z2)
go_result go_cubic_solve (const go_cubic *cub, go_complex *z1, go_complex *z2, go_complex *z3)
go_result go_quartic_solve (const go_quartic *quart, go_complex *z1, go_complex *z2, go_complex *z3, go_complex *z4)
go_result go_tridiag_reduce (go_real **a, go_integer n, go_real *d, go_real *e)
go_result go_tridiag_ql (go_real *d, go_real *e, go_integer n, go_real **z)
go_result go_cart_cart_pose (const go_cart *v1, const go_cart *v2, go_cart *v1c, go_cart *v2c, go_integer num, go_pose *pout)
go_result go_cart_trilaterate (const go_cart *c1, const go_cart *c2, const go_cart *c3, go_real l1, go_real l2, go_real l3, go_cart *out1, go_cart *out2)
go_flag go_rvec_rvec_compare (const go_rvec *r1, const go_rvec *r2)
go_result go_rvec_scale_mult (const go_rvec *r, go_real s, go_rvec *rout)
go_result go_rpy_cart_mult (const go_rpy *rpy, const go_cart *in, go_cart *out)
go_result go_mat_norm (const go_mat *mat, go_mat *mout)
go_flag go_mat_is_norm (const go_mat *m)
go_result go_mat_inv (const go_mat *m, go_mat *mout)
go_result go_mat_cart_mult (const go_mat *m, const go_cart *v, go_cart *vout)
go_result go_mat_mat_mult (const go_mat *m1, const go_mat *m2, go_mat *mout)
go_flag go_quat_quat_compare (const go_quat *q1, const go_quat *q2)
go_result go_quat_mag (const go_quat *quat, go_real *d)
go_result go_quat_unit (const go_quat *q1, go_quat *qout)
go_result go_quat_norm (const go_quat *q1, go_quat *qout)
go_result go_quat_inv (const go_quat *q1, go_quat *qout)
go_flag go_quat_is_norm (const go_quat *q1)
go_result go_quat_scale_mult (const go_quat *q, go_real s, go_quat *qout)
go_result go_quat_quat_mult (const go_quat *q1, const go_quat *q2, go_quat *qout)
go_result go_quat_cart_mult (const go_quat *q1, const go_cart *v2, go_cart *vout)
go_flag go_pose_pose_compare (const go_pose *p1, const go_pose *p2)
go_result go_pose_inv (const go_pose *p1, go_pose *p2)
go_result go_pose_cart_mult (const go_pose *p1, const go_cart *v2, go_cart *vout)
go_result go_pose_pose_mult (const go_pose *p1, const go_pose *p2, go_pose *pout)
go_result go_pose_scale_mult (const go_pose *p1, go_real s, go_pose *pout)
go_result go_pose_pose_interp (go_real t1, const go_pose *p1, go_real t2, const go_pose *p2, go_real t3, go_pose *p3)
go_result go_hom_inv (const go_hom *h1, go_hom *h2)
go_result go_hom_hom_mult (const go_hom *h1, const go_hom *h2, go_hom *hout)
go_result go_pose_vel_mult (const go_pose *pose, const go_vel *vel, go_vel *out)
go_result go_line_from_point_direction (const go_cart *point, const go_cart *direction, go_line *line)
go_result go_line_from_points (const go_cart *point1, const go_cart *point2, go_line *line)
go_result go_line_from_planes (const go_plane *plane1, const go_plane *plane2, go_line *line)
go_flag go_line_line_compare (const go_line *line1, const go_line *line2)
go_result go_line_evaluate (const go_line *line, go_real d, go_cart *point)
go_result go_point_line_distance (const go_cart *point, const go_line *line, go_real *distance)
go_result go_point_line_proj (const go_cart *point, const go_line *line, go_cart *pout)
go_result go_point_plane_proj (const go_cart *point, const go_plane *plane, go_cart *proj)
go_result go_line_plane_proj (const go_line *line, const go_plane *plane, go_line *proj)
go_result go_plane_from_point_normal (const go_cart *point, const go_cart *normal, go_plane *plane)
go_result go_plane_from_abcd (go_real A, go_real B, go_real C, go_real D, go_plane *plane)
go_result go_plane_from_points (const go_cart *point1, const go_cart *point2, const go_cart *point3, go_plane *plane)
go_result go_plane_from_point_line (const go_cart *point, const go_line *line, go_plane *plane)
go_flag go_plane_plane_compare (const go_plane *plane1, const go_plane *plane2)
go_result go_point_plane_distance (const go_cart *point, const go_plane *plane, go_real *distance)
go_result go_plane_evaluate (const go_plane *plane, go_real u, go_real v, go_cart *point)
go_result go_line_plane_intersect (const go_line *line, const go_plane *plane, go_cart *point, go_real *distance)
go_real go_get_singular_epsilon (void)
go_result go_set_singular_epsilon (go_real epsilon)
go_result ludcmp (go_real **a, go_real *scratchrow, go_integer n, go_integer *indx, go_real *d)
go_result lubksb (go_real **a, go_integer n, go_integer *indx, go_real *b)
go_result go_cart_vector_convert (const go_cart *c, go_real *v)
go_result go_vector_cart_convert (const go_real *v, go_cart *c)
go_result go_quat_matrix_convert (const go_quat *quat, go_matrix *matrix)
go_result go_mat_matrix_convert (const go_mat *mat, go_matrix *matrix)
go_result go_matrix_matrix_add (const go_matrix *a, const go_matrix *b, go_matrix *apb)
go_result go_matrix_matrix_copy (const go_matrix *src, go_matrix *dst)
go_result go_matrix_matrix_mult (const go_matrix *a, const go_matrix *b, go_matrix *ab)
go_result go_matrix_vector_mult (const go_matrix *a, const go_vector *v, go_vector *axv)
go_result go_matrix_vector_cross (const go_matrix *a, const go_vector *v, go_matrix *axv)
go_result go_matrix_transpose (const go_matrix *a, go_matrix *at)
go_result go_matrix_inv (const go_matrix *m, go_matrix *minv)
go_result go_mat3_inv (go_real a[3][3], go_real ainv[3][3])
go_result go_mat3_mat3_mult (go_real a[3][3], go_real b[3][3], go_real axb[3][3])
go_result go_mat3_vec3_mult (go_real a[3][3], go_real v[3], go_real axv[3])
go_result go_mat4_inv (go_real a[4][4], go_real ainv[4][4])
go_result go_mat4_mat4_mult (go_real a[4][4], go_real b[4][4], go_real axb[4][4])
go_result go_mat4_vec4_mult (go_real a[4][4], go_real v[4], go_real axv[4])
go_result go_mat6_inv (go_real a[6][6], go_real ainv[6][6])
go_result go_mat6_transpose (go_real a[6][6], go_real at[6][6])
go_result go_mat6_mat6_mult (go_real a[6][6], go_real b[6][6], go_real axb[6][6])
go_result go_mat6_vec6_mult (go_real a[6][6], go_real v[6], go_real axv[6])
go_result go_dh_hom_convert (const go_dh *dh, go_hom *h)
go_result go_dh_pose_convert (const go_dh *dh, go_pose *p)
go_result go_hom_dh_convert (const go_hom *h, go_dh *dh)
go_result go_pose_dh_convert (const go_pose *p, go_dh *dh)
go_result go_link_joint_set (const go_link *link, go_real joint, go_link *linkout)
go_result go_link_pose_build (const go_link *link_params, go_integer num, go_pose *pose)
go_result go_linear_cos_sin_solve (go_real a, go_real b, go_real *th1, go_real *th2)
go_result go_rvec_xyz_convert (const go_rvec *, go_xyz *)
go_result go_quat_xyz_convert (const go_quat *, go_xyz *)
go_result go_zyz_xyz_convert (const go_zyz *, go_xyz *)
go_result go_zyx_xyz_convert (const go_zyx *, go_xyz *)
go_result go_xyz_rvec_convert (const go_xyz *, go_rvec *)
go_result go_xyz_quat_convert (const go_xyz *, go_quat *)
go_result go_xyz_zyz_convert (const go_xyz *, go_zyz *)
go_result go_xyz_zyx_convert (const go_xyz *, go_zyx *)
go_result go_xyz_rpy_convert (const go_xyz *, go_rpy *)
go_result go_rpy_xyz_convert (const go_rpy *, go_xyz *)
go_result go_traj_ca_generate (go_real acc, go_real deltacc, go_real deltvel, go_traj_ca_spec *pts)
go_traj_ca_generate() takes an accel value, and intervals for the accel period and cruise period, and fills in the go_traj_ca_spec with the interval parameters.
go_result go_traj_ca_compute (go_real d, go_real v, go_real a, go_traj_ca_spec *pts)
go_traj_ca_compute() takes values for distance 'd' to move, max velocity 'v' to limit if necessary, and constant accel 'a', and fills in the go_traj_ca_spec with the interval parameters.
go_result go_traj_ca_scale (const go_traj_ca_spec *ts, go_real t, go_traj_ca_spec *pts)
go_traj_ca_scale() takes a time 't' for the desired time of the motion, and scales the times and motion params so that the total distance remains the same and everything else is in proportion
go_result go_traj_ca_stop (const go_traj_ca_spec *ts, go_real t, go_traj_ca_spec *pts)
go_traj_ca_stop() takes a time 't' for the desired time to begin stopping, and recomputes the times so that the move will stop as soon as possible during subsequent interps.
go_result go_traj_ca_extend (const go_traj_ca_spec *ts, go_real t, go_traj_ca_spec *pts)
go_traj_ca_extend() takes a time 't' for the desired time to finish the motion, and extends the constant-speed section so that it stops then.
go_result go_traj_ca_interp (const go_traj_ca_spec *ts, go_real t, go_traj_interp_spec *ti)
go_traj_ca_interp() takes a go_traj_ca_spec and interpolates the d-v-a values for the given time t, storing the d-v-a values in ti.
go_result go_traj_cj_generate (go_real jrk, go_real deltjrk, go_real deltacc, go_real deltvel, go_traj_cj_spec *pts)
go_traj_cj_generate() takes a jerk value, and intervals for the jerk period, accel period and cruise period, and fills in the go_traj_cj_spec with the interval parameters.
go_result go_traj_cj_compute (go_real d, go_real v, go_real a, go_real j, go_traj_cj_spec *pts)
go_traj_cj_compute() takes values for distance 'd' to move, max velocity 'v' to limit if necessary, max accel 'a' to limit if necessary, and constant jerk 'j', and fills in the go_traj_cj_spec with the interval parameters.
go_result go_traj_cj_scale (const go_traj_cj_spec *ts, go_real t, go_traj_cj_spec *pts)
go_traj_cj_scale() takes a time 't' for the desired time of the motion, and scales the times and motion params so that the total distance remains the same and everything else is in proportion
go_result go_traj_cj_stop (const go_traj_cj_spec *ts, go_real t, go_traj_cj_spec *pts)
go_traj_cj_stop() takes a time 't' for the desired time to begin stopping, and recomputes the times so that the move will stop as soon as possible during subsequent interps.
go_result go_traj_cj_extend (const go_traj_cj_spec *ts, go_real t, go_traj_cj_spec *pts)
go_traj_cj_extend() takes a time 't' for the desired time to finish the motion, and extends the constant-speed section so that it stops then.
go_result go_traj_cj_interp (const go_traj_cj_spec *ts, go_real t, go_traj_interp_spec *ti)
go_traj_cj_interp() takes a go_traj_cj_spec and interpolates the d-v-a-j values for the given time t, storing the d-v-a-j values in ti.
go_result go_traj_cj_compute_the_rest (go_traj_cj_spec *pts)
! Expects pts attributes dtend, jt0, at1, vt3, t1, t2 and t3 to be already filled in from previous calls to one of the four go_traj_cj_compute_tees functions and go_traj_cj_compute.
go_result go_traj_cj_compute_tees_na_nc (go_traj_cj_spec *pts)
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration or cruise phase, given pts filled in with dtend and jt0.
go_result go_traj_cj_compute_tees_a_nc (go_traj_cj_spec *pts)
! Computes the trajectory defining times t1, t2 and t4 for a motion with acceleration but no cruise phase, given pts filled in with dtend, jt0 and at1.
go_result go_traj_cj_compute_tees_na_c (go_traj_cj_spec *pts)
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration but a cruise phase, given pts filled in with dtend, jt0 and vt3.
go_result go_traj_cj_compute_tees_a_c (go_traj_cj_spec *pts)
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration but a cruise phase, given pts filled in with dtend, jt0, at1 and vt3.
Typedef Documentation
typedef go_real gomotion::go_vector
Declare a matrix variable m with rows rows and cols columns. Allocates rows X columns of space in mspace.
Definition at line 843 of file gomath.h.
typedef sensor_msgs::JointState_<std::allocator<void> > gomotion::JointState
Definition at line 21 of file gomove.h.
Enumeration Type Documentation
anonymous enum
How many coefficients we support, one more than max polynomial degree.
Enumerator
COEFF_MAX
Definition at line 13 of file gointerp.h.
anonymous enum
Types of link parameter representations
Enumerator
GO_LINK_DH
for Denavit-Hartenberg params
GO_LINK_PK
for parallel kinematics
GO_LINK_PP
for serial kinematics
Definition at line 1089 of file gomath.h.
anonymous enum
Enumerator
GO_MOTION_NONE
types of motion queueing done
GO_MOTION_JOINT
GO_MOTION_UJOINT
GO_MOTION_WORLD
GO_MOTION_LINEAR
these are used to further specify types of world motion
GO_MOTION_CIRCULAR
Definition at line 27 of file gomotion.h.
Function Documentation
go_result gomotion::go_acoses (go_real c, go_real * acp, go_real * acn)
Double-valued inverse cosine, giving both solutions
Definition at line 72 of file gomath.cpp.
References GO_RESULT_DOMAIN_ERROR, and GO_RESULT_OK.
go_result gomotion::go_asines (go_real s, go_real * asp, go_real * asn)
Double-valued inverse sine, giving both solutions
Definition at line 57 of file gomath.cpp.
References GO_PI, GO_RESULT_DOMAIN_ERROR, and GO_RESULT_OK.
go_result gomotion::go_atans (go_real t, go_real * atp, go_real * atn)
Double-valued inverse tangent, giving both solutions
Definition at line 82 of file gomath.cpp.
References GO_PI, and GO_RESULT_OK.
go_result gomotion::go_cart_cart_add (const go_cart * v1, const go_cart * v2, go_cart * vout)
Definition at line 1064 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_hom_hom_mult(), go_line_evaluate(), go_plane_evaluate(), go_point_line_proj(), go_pose_cart_mult(), go_pose_pose_mult(), go_pose_vel_mult(), and gomotion::go_motion_queue::interp_world().
go_result gomotion::go_cart_cart_angle (const go_cart * v1, const go_cart * v2, go_real * a)
Definition at line 1213 of file gomath.cpp.
References go_cart_cart_dot(), go_cart_mag(), GO_RESULT_DIV_ERROR, and GO_RESULT_OK.
Referenced by gomotion::go_motion_queue::append_world().
go_flag gomotion::go_cart_cart_compare (const go_cart * v1, const go_cart * v2)
Definition at line 978 of file gomath.cpp.
References GO_TRAN_CLOSE, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_mat_is_norm(), go_plane_plane_compare(), and go_pose_pose_compare().
go_result gomotion::go_cart_cart_cross (const go_cart * v1, const go_cart * v2, go_cart * vout)
Definition at line 997 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_rot(), go_cart_normal(), go_cart_trilaterate(), go_line_from_planes(), go_mat_is_norm(), go_mat_norm(), go_matrix_vector_cross(), go_plane_evaluate(), go_plane_from_points(), go_pose_vel_mult(), and go_uxz_mat_convert().
go_result gomotion::go_cart_cart_disp (const go_cart * v1, const go_cart * v2, go_real * disp)
Places the Cartesian displacement between two vectors v1 and v2 in disp, returning GO_RESULT_OK.
Definition at line 1054 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_cart_cart_dot (const go_cart * v1, const go_cart * v2, go_real * d)
Definition at line 989 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_angle(), go_cart_cart_par(), go_cart_cart_perp(), go_cart_cart_proj(), go_cart_cart_rot(), go_line_line_compare(), and go_line_plane_intersect().
go_flag gomotion::go_cart_cart_par (const go_cart * v1, const go_cart * v2)
Definition at line 1026 of file gomath.cpp.
References go_cart_cart_dot(), go_cart_magsq(), and GO_TRAN_CLOSE.
go_flag gomotion::go_cart_cart_perp (const go_cart * v1, const go_cart * v2)
Definition at line 1043 of file gomath.cpp.
References go_cart_cart_dot(), and GO_TRAN_SMALL.
go_result gomotion::go_cart_cart_pose (const go_cart * v1, const go_cart * v2, go_cart * v1c, go_cart * v2c, go_integer num, go_pose * pout)
Given an array of Cartesian points measured in one coordinate system, and an associated array measured in another coordinate system, returns the best-fit transform that takes points in the first coordinate system to their representation in the second coordinate system.
Parameters
v1 An array of Cartesian points in one coordinate system
v2 An array of the same Cartesian points in another coordinate system
v1c A scratch array of the same size as v1 needed for calculation.
v2c A scratch array of the same size as v2 needed for calculation.
num The number of points in the v1 and v2 arrays, which must be the same size.
pout A pointer to the calculated best-fit pose filled in by this function.
Definition at line 2026 of file gomath.cpp.
References go_cart_cart_sub(), go_cart_centroidize(), GO_MATRIX_DECLARE, go_matrix_init, go_quat_cart_mult(), go_quat_norm(), GO_RESULT_OK, go_tridiag_ql(), go_tridiag_reduce(), gomotion::go_pose::rot, gomotion::go_quat::s, gomotion::go_pose::tran, gomotion::go_cart::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_quat::y, gomotion::go_cart::z, and gomotion::go_quat::z.
go_result gomotion::go_cart_cart_proj (const go_cart * v1, const go_cart * v2, go_cart * vout)
Project vector v1 onto v2, with the resulting vector placed into vout. Returns GO_RESULT_OK if it can be done, otherwise something else.
Definition at line 1185 of file gomath.cpp.
References go_cart_cart_dot(), go_cart_scale_mult(), go_cart_unit(), and GO_RESULT_OK.
Referenced by go_cart_plane_proj(), go_cart_trilaterate(), go_mat_norm(), go_point_line_proj(), and go_uxz_mat_convert().
go_result gomotion::go_cart_cart_rot (const go_cart * v1, const go_cart * v2, go_quat * quat)
Given two non-zero vectors v1 and v2, fill in quat with the minimum rotation that brings v1 to v2.
Definition at line 1128 of file gomath.cpp.
References go_cart_cart_cross(), go_cart_cart_dot(), go_cart_mag(), go_cart_normal(), go_cart_unit(), GO_PI, GO_RESULT_OK, go_rvec_quat_convert(), gomotion::go_quat::s, gomotion::go_cart::x, gomotion::go_rvec::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_rvec::y, gomotion::go_quat::y, gomotion::go_cart::z, gomotion::go_rvec::z, and gomotion::go_quat::z.
go_result gomotion::go_cart_cart_sub (const go_cart * v1, const go_cart * v2, go_cart * vout)
Definition at line 1074 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_pose(), go_cart_centroidize(), go_cart_plane_proj(), go_cart_trilaterate(), go_line_from_points(), go_line_line_compare(), go_mat_norm(), go_plane_from_points(), go_point_line_proj(), and go_uxz_mat_convert().
go_result gomotion::go_cart_centroid (const go_cart * varray, go_integer num, go_cart * centroid)
Definition at line 1261 of file gomath.cpp.
References go_cart_scale_mult(), GO_RESULT_BAD_ARGS, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_cart_centroidize().
go_result gomotion::go_cart_centroidize (const go_cart * vinarray, go_integer num, go_cart * centroid, go_cart * voutarray)
Definition at line 1282 of file gomath.cpp.
References go_cart_cart_sub(), go_cart_centroid(), and GO_RESULT_OK.
Referenced by go_cart_cart_pose().
go_result gomotion::go_cart_cyl_convert (const go_cart * v, go_cyl * c)
Definition at line 223 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_cyl::r, gomotion::go_cyl::theta, gomotion::go_cart::x, gomotion::go_cart::y, gomotion::go_cart::z, and gomotion::go_cyl::z.
go_result gomotion::go_cart_is_norm (const go_cart * v)
Definition at line 1123 of file gomath.cpp.
References go_sq, GO_TRAN_CLOSE, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_cart_mag (const go_cart * v, go_real * d)
Definition at line 1012 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_angle(), go_cart_cart_rot(), go_rvec_mat_convert(), and go_rvec_quat_convert().
go_result gomotion::go_cart_magsq (const go_cart * v, go_real * d)
Definition at line 1019 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_cart_cart_par().
go_result gomotion::go_cart_neg (const go_cart * v1, go_cart * vout)
Definition at line 1093 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_cart_normal (const go_cart * v, go_cart * vout)
go_cart_normal finds one of the infinite vectors perpendicular to v, putting the result in vout.
Definition at line 1237 of file gomath.cpp.
References go_cart_cart_cross(), go_cart_unit(), gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_cart_cart_rot(), and go_plane_evaluate().
go_result gomotion::go_cart_plane_proj (const go_cart * v, const go_cart * normal, go_cart * vout)
Definition at line 1201 of file gomath.cpp.
References go_cart_cart_proj(), go_cart_cart_sub(), and GO_RESULT_OK.
Referenced by gomotion::go_motion_queue::append_world(), and go_line_plane_proj().
go_result gomotion::go_cart_rvec_convert (const go_cart * cart, go_rvec * rvec)
go_cart_rvec_convert and go_rvec_cart_convert convert between Cartesian vectors and rotation vectors. The conversion is trivial but keeps types distinct.
Definition at line 958 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_rvec::x, gomotion::go_cart::y, gomotion::go_rvec::y, gomotion::go_cart::z, and gomotion::go_rvec::z.
Referenced by gomotion::go_motion_queue::append_world().
go_result gomotion::go_cart_scale_mult (const go_cart * v1, go_real d, go_cart * vout)
Definition at line 1084 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_cart_cart_proj(), go_cart_centroid(), go_line_evaluate(), go_plane_evaluate(), go_pose_scale_mult(), and gomotion::go_motion_queue::interp_world().
go_result gomotion::go_cart_sph_convert (const go_cart * v, go_sph * s)
Definition at line 207 of file gomath.cpp.
References GO_RESULT_OK, go_sq, GO_TRAN_SMALL, gomotion::go_sph::phi, gomotion::go_sph::r, gomotion::go_sph::theta, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_cart_trilaterate (const go_cart * c1, const go_cart * c2, const go_cart * c3, go_real l1, go_real l2, go_real l3, go_cart * out1, go_cart * out2)
Returns the Cartesian point p whose distances from three other points c1, c2 and c3 are l1, l2 and l3, respectively. In general there are 0, 1 or two points possible. If no point is possible, this returns GO_RESULT_ERROR, otherwise the points are returned in p1 and p2, which may be the same point.
Definition at line 2133 of file gomath.cpp.
References go_cart_cart_cross(), go_cart_cart_proj(), go_cart_cart_sub(), go_cart_unit(), go_mat_quat_convert(), go_pose_cart_mult(), go_pose_inv(), GO_RESULT_OK, gomotion::go_pose::rot, gomotion::go_pose::tran, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
go_result gomotion::go_cart_unit (const go_cart * v, go_cart * vout)
Definition at line 1102 of file gomath.cpp.
References GO_INF, GO_RESULT_NORM_ERROR, GO_RESULT_OK, go_sq, GO_TRAN_SMALL, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_proj(), go_cart_cart_rot(), go_cart_normal(), go_cart_trilaterate(), go_line_from_planes(), go_line_from_point_direction(), go_line_from_points(), go_mat_norm(), go_plane_from_point_normal(), go_plane_from_points(), go_rvec_mat_convert(), go_rvec_quat_convert(), go_uxz_mat_convert(), and gomotion::go_motion_spec::set_cpar().
go_result gomotion::go_cart_vector_convert (const go_cart * c, go_real * v)
Definition at line 3101 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_cart gomotion::go_cart_zero (void)
Returns the zero vector.
Definition at line 916 of file gomath.cpp.
References gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_real gomotion::go_cbrt (go_real x)
Returns the cube root of x.
Definition at line 104 of file gomath.cpp.
Referenced by go_complex_cbrt(), go_cubic_solve(), and go_traj_cj_compute_tees_na_nc().
go_complex gomotion::go_complex_add (go_complex z1, go_complex z2)
Definition at line 1446 of file gomath.cpp.
References gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_cubic_solve(), and go_quartic_solve().
go_real gomotion::go_complex_arg (go_complex z)
Definition at line 1533 of file gomath.cpp.
References gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_complex_cbrt(), and go_complex_sqrt().
void gomotion::go_complex_cbrt (go_complex z, go_complex * z1, go_complex * z2, go_complex * z3)
Definition at line 1562 of file gomath.cpp.
References go_cbrt(), go_complex_arg(), go_complex_mag(), GO_PI, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_cubic_solve().
go_complex gomotion::go_complex_div (go_complex z1, go_complex z2, go_result * result)
Definition at line 1492 of file gomath.cpp.
References go_complex_mult(), go_complex_scale(), GO_REAL_EPSILON, GO_RESULT_DIV_ERROR, GO_RESULT_OK, go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
go_complex gomotion::go_complex_inv (go_complex z, go_result * result)
Definition at line 1476 of file gomath.cpp.
References go_complex_scale(), GO_REAL_EPSILON, GO_RESULT_DIV_ERROR, GO_RESULT_OK, go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_quartic_solve().
go_real gomotion::go_complex_mag (go_complex z)
Definition at line 1523 of file gomath.cpp.
References go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_complex_cbrt(), and go_complex_sqrt().
go_real gomotion::go_complex_magsq (go_complex z)
Definition at line 1528 of file gomath.cpp.
References go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_quartic_solve().
go_complex gomotion::go_complex_mult (go_complex z1, go_complex z2)
Definition at line 1466 of file gomath.cpp.
References gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_complex_div(), go_complex_sq(), go_cubic_solve(), and go_quartic_solve().
go_complex gomotion::go_complex_scale (go_complex z, go_real scale)
Definition at line 1513 of file gomath.cpp.
References gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_complex_div(), go_complex_inv(), go_cubic_solve(), and go_quartic_solve().
go_complex gomotion::go_complex_sq (go_complex z)
Definition at line 1508 of file gomath.cpp.
References go_complex_mult().
void gomotion::go_complex_sqrt (go_complex z, go_complex * z1, go_complex * z2)
Definition at line 1545 of file gomath.cpp.
References go_complex_arg(), go_complex_mag(), gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_cubic_solve(), and go_quartic_solve().
go_complex gomotion::go_complex_sub (go_complex z1, go_complex z2)
Definition at line 1456 of file gomath.cpp.
References gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_cubic_solve(), and go_quartic_solve().
go_result gomotion::go_cubic_solve (const go_cubic * cub, go_complex * z1, go_complex * z2, go_complex * z3)
Definition at line 1622 of file gomath.cpp.
References gomotion::go_quadratic::a, gomotion::go_cubic::a, gomotion::go_quadratic::b, gomotion::go_cubic::b, gomotion::go_cubic::c, go_cbrt(), go_complex_add(), go_complex_cbrt(), go_complex_mult(), go_complex_scale(), go_complex_sqrt(), go_complex_sub(), go_cub, go_quadratic_solve(), GO_RESULT_OK, GO_SMALL, go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_quartic_solve().
go_result gomotion::go_cyl_cart_convert (const go_cyl * c, go_cart * v)
Definition at line 259 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cyl::r, gomotion::go_cyl::theta, gomotion::go_cart::x, gomotion::go_cart::y, gomotion::go_cart::z, and gomotion::go_cyl::z.
go_result gomotion::go_cyl_sph_convert (const go_cyl * c, go_sph * s)
Definition at line 268 of file gomath.cpp.
References GO_RESULT_OK, go_sq, GO_TRAN_SMALL, gomotion::go_sph::phi, gomotion::go_sph::r, gomotion::go_cyl::r, gomotion::go_sph::theta, gomotion::go_cyl::theta, and gomotion::go_cyl::z.
go_result gomotion::go_dh_hom_convert (const go_dh * dh, go_hom * hom)
Converts DH parameters in dh to their transform equivalent, stored in hom.
Definition at line 3962 of file gomath.cpp.
References gomotion::go_dh::a, gomotion::go_dh::alpha, gomotion::go_dh::d, GO_RESULT_OK, go_sincos(), gomotion::go_hom::rot, gomotion::go_dh::theta, gomotion::go_hom::tran, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_dh_pose_convert().
go_result gomotion::go_dh_pose_convert (const go_dh * dh, go_pose * pose)
Converts DH parameters in dh to their pose equivalent, stored in pose.
Definition at line 3981 of file gomath.cpp.
References go_dh_hom_convert(), and go_hom_pose_convert().
Referenced by go_link_pose_build().
go_real gomotion::go_get_singular_epsilon (void)
Definition at line 2980 of file gomath.cpp.
go_result gomotion::go_hom_dh_convert (const go_hom * hom, go_dh * dh)
Counterpart to go_pose_dh_convert, for transforms.
Definition at line 3989 of file gomath.cpp.
References gomotion::go_dh::a, gomotion::go_dh::alpha, gomotion::go_dh::d, GO_RESULT_OK, GO_ROT_SMALL, gomotion::go_hom::rot, gomotion::go_dh::theta, gomotion::go_hom::tran, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_pose_dh_convert().
go_result gomotion::go_hom_hom_mult (const go_hom * h1, const go_hom * h2, go_hom * hout)
Definition at line 2599 of file gomath.cpp.
References go_cart_cart_add(), go_mat_cart_mult(), go_mat_mat_mult(), GO_RESULT_OK, gomotion::go_hom::rot, and gomotion::go_hom::tran.
go_result gomotion::go_hom_inv (const go_hom * h1, go_hom * h2)
Definition at line 2582 of file gomath.cpp.
References go_mat_cart_mult(), go_mat_inv(), GO_RESULT_OK, gomotion::go_hom::rot, gomotion::go_hom::tran, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_hom_pose_convert (const go_hom * h, go_pose * p)
Definition at line 951 of file gomath.cpp.
References go_mat_quat_convert(), gomotion::go_pose::rot, gomotion::go_hom::rot, gomotion::go_pose::tran, and gomotion::go_hom::tran.
Referenced by go_dh_pose_convert().
go_result gomotion::go_line_evaluate (const go_line * line, go_real d, go_cart * point)
Fills in point with the point located distance d along line
Definition at line 2752 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_cart_add(), go_cart_scale_mult(), GO_RESULT_OK, and gomotion::go_line::point.
Referenced by go_line_plane_intersect(), and go_plane_from_point_line().
go_result gomotion::go_line_from_planes (const go_plane * plane1, const go_plane * plane2, go_line * line)
Fill in line with the intersection of the two planes. Returns GO_RESULT_OK if the planes are not parallel, otherwise GO_RESULT_ERROR.
Definition at line 2677 of file gomath.cpp.
References gomotion::go_plane::d, gomotion::go_line::direction, go_cart_cart_cross(), go_cart_unit(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_plane::normal, gomotion::go_line::point, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_line_from_point_direction (const go_cart * point, const go_cart * direction, go_line * line)
Fills in line given point and direction. Returns GO_RESULT_OK if direction is non-zero, otherwise GO_RESULT_ERROR.
Definition at line 2651 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_unit(), GO_RESULT_DIV_ERROR, GO_RESULT_OK, and gomotion::go_line::point.
go_result gomotion::go_line_from_points (const go_cart * point1, const go_cart * point2, go_line * line)
Fills in line given two points. Returns GO_RESULT_OK if the points are different, otherwise GO_RESULT_ERROR.
Definition at line 2663 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_cart_sub(), go_cart_unit(), GO_RESULT_DIV_ERROR, GO_RESULT_OK, and gomotion::go_line::point.
go_flag gomotion::go_line_line_compare (const go_line * line1, const go_line * line2)
Returns non-zero if the lines are the same, otherwise zero.
Definition at line 2735 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_cart_dot(), go_cart_cart_sub(), GO_CLOSE, and gomotion::go_line::point.
go_result gomotion::go_line_plane_intersect (const go_line * line, const go_plane * plane, go_cart * point, go_real * distance)
Fills in point with the intersection point of line with plane, and distance with the distance along the line to the intersection point. Returns GO_RESULT_ERROR if the line is parallel to the plane and not lying in the plane, otherwise GO_RESULT_OK.
Definition at line 2936 of file gomath.cpp.
References gomotion::go_plane::d, gomotion::go_line::direction, go_cart_cart_dot(), go_line_evaluate(), go_point_plane_distance(), GO_RESULT_ERROR, GO_SMALL, gomotion::go_plane::normal, and gomotion::go_line::point.
go_result gomotion::go_line_plane_proj (const go_line * line, const go_plane * plane, go_line * proj)
Fills in proj with the projection of line onto plane
Definition at line 2812 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_plane_proj(), go_point_plane_proj(), GO_RESULT_OK, gomotion::go_plane::normal, and gomotion::go_line::point.
go_result gomotion::go_linear_cos_sin_solve (go_real a, go_real b, go_real * th1, go_real * th2)
Solves cos theta + b sin theta = 1 for theta, two solutions
Definition at line 4114 of file gomath.cpp.
References GO_PI, GO_REAL_EPSILON, GO_RESULT_DOMAIN_ERROR, GO_RESULT_OK, and GO_ROT_CLOSE.
go_result gomotion::go_link_joint_set (const go_link * link, go_real joint, go_link * linkout)
Fixes the link in link to its value when the joint variable is joint, storing the result in linkout.
Definition at line 4011 of file gomath.cpp.
References gomotion::go_dh::a, gomotion::go_dh::alpha, gomotion::go_pk::base, gomotion::go_link::body, gomotion::go_dh::d, gomotion::go_pk::d, gomotion::go_link::dh, GO_LINK_DH, GO_LINK_PK, GO_LINK_PP, go_pose_identity(), go_pose_pose_mult(), GO_QUANTITY_LENGTH, GO_RESULT_ERROR, GO_RESULT_IMPL_ERROR, GO_RESULT_OK, go_rvec_quat_convert(), gomotion::go_body::inertia, gomotion::go_body::mass, gomotion::go_link::pk, gomotion::go_pk::platform, gomotion::go_pp::pose, gomotion::go_link::pp, gomotion::go_link::quantity, gomotion::go_pose::rot, gomotion::go_dh::theta, gomotion::go_pose::tran, gomotion::go_link::type, gomotion::go_link::u, gomotion::go_rvec::x, gomotion::go_rvec::y, gomotion::go_cart::z, and gomotion::go_rvec::z.
go_result gomotion::go_link_pose_build (const go_link * links, go_integer num, go_pose * pose)
Takes the link description of the device in links, and the number of these in num, and builds the pose of the device and stores in pose. links should have the value of the free link parameter filled in with the current joint value, e.g., with a prior call to go_link_joint_set.
Definition at line 4074 of file gomath.cpp.
References gomotion::go_link::dh, go_dh_pose_convert(), GO_LINK_DH, GO_LINK_PP, go_pose_identity(), go_pose_pose_mult(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_pp::pose, and gomotion::go_link::pp.
go_result gomotion::go_mat3_inv (go_real a[3][3], go_real ainv[3][3])
Definition at line 3406 of file gomath.cpp.
References GO_RESULT_OK, GO_RESULT_SINGULAR, and GO_SMALL.
go_result gomotion::go_mat3_mat3_mult (go_real a[3][3], go_real b[3][3], go_real axb[3][3])
Definition at line 3488 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat3_vec3_mult (go_real a[3][3], go_real v[3], go_real axv[3])
Definition at line 3511 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat4_inv (go_real a[4][4], go_real ainv[4][4])
Definition at line 3531 of file gomath.cpp.
References GO_RESULT_OK, GO_RESULT_SINGULAR, and GO_SMALL.
go_result gomotion::go_mat4_mat4_mult (go_real a[4][4], go_real b[4][4], go_real axb[4][4])
Definition at line 3816 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat4_vec4_mult (go_real a[4][4], go_real v[4], go_real axv[4])
Definition at line 3839 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat6_inv (go_real a[6][6], go_real ainv[6][6])
Given a 6x6 matrix a, computes the inverse and returns it in ainv. Leaves a untouched. Returns GO_RESULT_OK if there is an inverse, else GO_RESULT_SINGULAR if the matrix is singular.
Definition at line 3859 of file gomath.cpp.
References GO_RESULT_OK, lubksb(), and ludcmp().
go_result gomotion::go_mat6_mat6_mult (go_real a[6][6], go_real b[6][6], go_real axb[6][6])
Given two 6x6 matrices a and b, multiplies them and returns the result in axb. Leaves a and b untouched. Returns GO_RESULT_OK.
Definition at line 3914 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat6_transpose (go_real a[6][6], go_real at[6][6])
Given a 6x6 matrix a, generates the transpose and returns it in at. Leaves a untouched. Returns GO_RESULT_OK.
Definition at line 3900 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat6_vec6_mult (go_real a[6][6], go_real v[6], go_real axv[6])
Given a 6x6 matrix a and a 6x1 vector v, multiplies them and returns the result in axv. Leaves a and v untouched. Returns GO_RESULT_OK.
Definition at line 3937 of file gomath.cpp.
References GO_RESULT_OK.
go_result gomotion::go_mat_cart_mult (const go_mat * m, const go_cart * v, go_cart * vout)
Definition at line 2276 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_hom_hom_mult(), and go_hom_inv().
go_result gomotion::go_mat_inv (const go_mat * m, go_mat * mout)
Definition at line 2251 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_hom_inv().
go_flag gomotion::go_mat_is_norm (const go_mat * m)
Definition at line 2237 of file gomath.cpp.
References COL_IS_UNIT, go_cart_cart_compare(), go_cart_cart_cross(), gomotion::go_mat::x, gomotion::go_mat::y, and gomotion::go_mat::z.
Referenced by go_mat_quat_convert().
go_result gomotion::go_mat_mat_mult (const go_mat * m1, const go_mat * m2, go_mat * mout)
Definition at line 2290 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_hom_hom_mult().
go_result gomotion::go_mat_matrix_convert (const go_mat * mat, go_matrix * matrix)
Definition at line 3140 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_matrix::rows, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_quat_matrix_convert().
go_result gomotion::go_mat_norm (const go_mat * m, go_mat * mout)
Normalizes rotation matrix m so that all columns are mutually perpendicular unit vectors, placing the result in mout.
Definition at line 2217 of file gomath.cpp.
References go_cart_cart_cross(), go_cart_cart_proj(), go_cart_cart_sub(), go_cart_unit(), GO_RESULT_OK, gomotion::go_mat::x, gomotion::go_mat::y, and gomotion::go_mat::z.
go_result gomotion::go_mat_quat_convert (const go_mat * m, go_quat * q)
Definition at line 500 of file gomath.cpp.
References go_mat_is_norm(), go_quat_norm(), GO_RESULT_NORM_ERROR, GO_ROT_SMALL, gomotion::go_quat::s, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_quat::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_quat::z.
Referenced by go_cart_trilaterate(), go_hom_pose_convert(), go_mat_rvec_convert(), go_rpy_quat_convert(), go_zyx_quat_convert(), and go_zyz_quat_convert().
go_result gomotion::go_mat_rpy_convert (const go_mat * m, go_rpy * rpy)
Definition at line 617 of file gomath.cpp.
References GO_PI_2, GO_RESULT_OK, GO_ROT_CLOSE, go_sq, gomotion::go_rpy::p, gomotion::go_rpy::r, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_rpy::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_quat_rpy_convert(), go_zyx_rpy_convert(), and go_zyz_rpy_convert().
go_result gomotion::go_mat_rvec_convert (const go_mat * m, go_rvec * r)
Definition at line 460 of file gomath.cpp.
References go_mat_quat_convert(), go_quat_rvec_convert(), and GO_RESULT_OK.
Referenced by go_zyx_rvec_convert(), and go_zyz_rvec_convert().
go_result gomotion::go_mat_uxz_convert (const go_mat * mat, go_uxz * uxz)
Definition at line 897 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_mat::x, gomotion::go_uxz::x, gomotion::go_mat::z, and gomotion::go_uxz::z.
go_result gomotion::go_mat_xyz_convert (const go_mat * m, go_xyz * xyz)
Definition at line 597 of file gomath.cpp.
References GO_PI_2, GO_RESULT_OK, GO_ROT_CLOSE, go_sq, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_xyz::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_xyz::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_xyz::z.
go_result gomotion::go_mat_zyx_convert (const go_mat * m, go_zyx * zyx)
Definition at line 577 of file gomath.cpp.
References GO_PI_2, GO_RESULT_OK, GO_ROT_CLOSE, go_sq, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_zyx::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_zyx::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_zyx::z.
Referenced by go_quat_zyx_convert(), go_rpy_zyx_convert(), go_rvec_zyx_convert(), and go_zyz_zyx_convert().
go_result gomotion::go_mat_zyz_convert (const go_mat * m, go_zyz * zyz)
Definition at line 557 of file gomath.cpp.
References GO_PI, GO_RESULT_OK, GO_ROT_CLOSE, GO_ROT_SMALL, go_sq, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_zyz::y, gomotion::go_cart::z, gomotion::go_mat::z, gomotion::go_zyz::z, and gomotion::go_zyz::zp.
Referenced by go_quat_zyz_convert(), go_rpy_zyz_convert(), go_rvec_zyz_convert(), and go_zyx_zyz_convert().
go_result gomotion::go_matrix_inv (const go_matrix * m, go_matrix * minv)
Definition at line 3367 of file gomath.cpp.
References gomotion::go_matrix::el, gomotion::go_matrix::elcpy, GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_matrix::index, lubksb(), ludcmp(), gomotion::go_matrix::rows, and gomotion::go_matrix::v.
go_result gomotion::go_matrix_matrix_add (const go_matrix * a, const go_matrix * b, go_matrix * apb)
Definition at line 3155 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_matrix_matrix_copy (const go_matrix * src, go_matrix * dst)
Definition at line 3176 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_matrix_matrix_mult (const go_matrix * a, const go_matrix * b, go_matrix * ab)
Definition at line 3195 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, gomotion::go_matrix::elcpy, GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_matrix_transpose (const go_matrix * a, go_matrix * at)
Definition at line 3332 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, gomotion::go_matrix::elcpy, GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_matrix_vector_cross (const go_matrix * a, const go_vector * v, go_matrix * axv)
The matrix-vector cross product is a matrix of the same dimension, whose columns are the column-wise cross products of the matrix and the vector. The matrices must be 3xN, the vector 3x1.
Definition at line 3282 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, gomotion::go_matrix::elcpy, go_cart_cart_cross(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_matrix::rows, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_matrix_vector_mult (const go_matrix * a, const go_vector * v, go_vector * axv)
Definition at line 3242 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, gomotion::go_matrix::elcpy, GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_plane_evaluate (const go_plane * plane, go_real u, go_real v, go_cart * point)
Fills in point with the point located distances u and v along some othogonal planar coordinate system in plane
Definition at line 2897 of file gomath.cpp.
References gomotion::go_plane::d, go_cart_cart_add(), go_cart_cart_cross(), go_cart_normal(), go_cart_scale_mult(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_plane_from_abcd (go_real A, go_real B, go_real C, go_real D, go_plane * plane)
Fills in plane given the A, B, C and D values in the canonical form Ax + By + Cz + D = 0. Returns GO_RESULT_OK if not all of A, B and C are zero, otherwise GO_RESULT_ERROR.
Definition at line 2833 of file gomath.cpp.
References gomotion::go_plane::d, GO_RESULT_DIV_ERROR, GO_RESULT_OK, go_sq, GO_TRAN_SMALL, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_plane_from_point_line (const go_cart * point, const go_line * line, go_plane * plane)
Fills in plane given a point on the plane and a line in the plane. Returns GO_RESULT_OK if the point is not on the line, GO_RESULT_ERROR otherwise.
Definition at line 2869 of file gomath.cpp.
References go_line_evaluate(), and go_plane_from_points().
go_result gomotion::go_plane_from_point_normal (const go_cart * point, const go_cart * normal, go_plane * plane)
Fills in plane give a point on the plane and the normal direction.
Definition at line 2822 of file gomath.cpp.
References gomotion::go_plane::d, go_cart_unit(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_plane_from_points (const go_cart * point1, const go_cart * point2, const go_cart * point3, go_plane * plane)
Fills in plane given three points. Returns GO_RESULT_OK if the points are distinct, otherwise GO_RESULT_ERROR.
Definition at line 2852 of file gomath.cpp.
References gomotion::go_plane::d, go_cart_cart_cross(), go_cart_cart_sub(), go_cart_unit(), GO_RESULT_ERROR, GO_RESULT_OK, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_plane_from_point_line().
go_flag gomotion::go_plane_plane_compare (const go_plane * plane1, const go_plane * plane2)
Returns non-zero if the planes are coincident and have the same normal direction, otherwise zero.
Definition at line 2881 of file gomath.cpp.
References gomotion::go_plane::d, go_cart_cart_compare(), GO_CLOSE, and gomotion::go_plane::normal.
go_result gomotion::go_point_line_distance (const go_cart * point, const go_line * line, go_real * distance)
Fills in distance with the distance from point to line
Definition at line 2762 of file gomath.cpp.
References gomotion::go_line::direction, GO_RESULT_OK, go_sq, gomotion::go_line::point, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_point_line_proj (const go_cart * point, const go_line * line, go_cart * pout)
Fills in pout with the nearest point on line to point
Definition at line 2775 of file gomath.cpp.
References gomotion::go_line::direction, go_cart_cart_add(), go_cart_cart_proj(), go_cart_cart_sub(), GO_RESULT_OK, and gomotion::go_line::point.
go_result gomotion::go_point_plane_distance (const go_cart * point, const go_plane * plane, go_real * distance)
Fills in the distance from the point to the plane.
Definition at line 2887 of file gomath.cpp.
References gomotion::go_plane::d, GO_RESULT_OK, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_line_plane_intersect().
go_result gomotion::go_point_plane_proj (const go_cart * point, const go_plane * plane, go_cart * proj)
Fills in proj with the projection of point onto plane
Definition at line 2788 of file gomath.cpp.
References gomotion::go_plane::d, GO_RESULT_DIV_ERROR, GO_RESULT_OK, go_sq, GO_TRAN_SMALL, gomotion::go_plane::normal, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_line_plane_proj().
go_result gomotion::go_pose_cart_mult (const go_pose * p1, const go_cart * v2, go_cart * vout)
Definition at line 2509 of file gomath.cpp.
References go_cart_cart_add(), go_quat_cart_mult(), GO_RESULT_OK, gomotion::go_pose::rot, and gomotion::go_pose::tran.
Referenced by go_cart_trilaterate().
go_result gomotion::go_pose_dh_convert (const go_pose * pose, go_dh * dh)
Converts pose to the equivalent DH parameters, stored in dh. Warning! Conversion from these DH parameters back to a pose via go_dh_pose_convert will NOT in general result in the same pose. Poses have 6 degrees of freedom, DH parameters have 4, and conversion to DH parameters loses some information. The source of this information loss is the convention imposed on DH parameters for choice of X-Y-Z axis directions. With poses, there is no such convention, and poses are thus freer than DH parameters.
Definition at line 4003 of file gomath.cpp.
References go_hom_dh_convert(), and go_pose_hom_convert().
go_result gomotion::go_pose_hom_convert (const go_pose * p, go_hom * h)
Definition at line 944 of file gomath.cpp.
References go_quat_mat_convert(), gomotion::go_pose::rot, gomotion::go_hom::rot, gomotion::go_pose::tran, and gomotion::go_hom::tran.
Referenced by go_pose_dh_convert().
go_pose gomotion::go_pose_identity (void)
Returns the identity pose, no translation or rotation.
Definition at line 934 of file gomath.cpp.
References gomotion::go_pose::rot, gomotion::go_quat::s, gomotion::go_pose::tran, gomotion::go_cart::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_quat::y, gomotion::go_cart::z, and gomotion::go_quat::z.
Referenced by go_link_joint_set(), and go_link_pose_build().
go_result gomotion::go_pose_inv (const go_pose * p1, go_pose * p2)
Definition at line 2492 of file gomath.cpp.
References go_quat_cart_mult(), go_quat_inv(), GO_RESULT_OK, gomotion::go_pose::rot, gomotion::go_pose::tran, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
Referenced by go_cart_trilaterate(), go_pose_pose_interp(), and go_pose_vel_mult().
go_flag gomotion::go_pose_pose_compare (const go_pose * p1, const go_pose * p2)
Definition at line 2486 of file gomath.cpp.
References go_cart_cart_compare(), go_quat_quat_compare(), gomotion::go_pose::rot, and gomotion::go_pose::tran.
go_result gomotion::go_pose_pose_interp (go_real t1, const go_pose * p1, go_real t2, const go_pose * p2, go_real t3, go_pose * p3)
Given two times t1 and t2, and associated poses p1 and p2, interpolates (or extrapolates) to find pose p3 at time t3. The result is stored in p3. Returns GO_RESULT_OK if t1 and t2 are distinct and p1 and p2 are valid poses, otherwise it can't interpolate and returns a relevant error.
Definition at line 2565 of file gomath.cpp.
References GO_CLOSE, go_pose_inv(), go_pose_pose_mult(), go_pose_scale_mult(), GO_RESULT_ERROR, and GO_RESULT_OK.
go_result gomotion::go_pose_pose_mult (const go_pose * p1, const go_pose * p2, go_pose * pout)
Definition at line 2541 of file gomath.cpp.
References go_cart_cart_add(), go_quat_cart_mult(), go_quat_quat_mult(), GO_RESULT_OK, gomotion::go_pose::rot, and gomotion::go_pose::tran.
Referenced by go_link_joint_set(), go_link_pose_build(), and go_pose_pose_interp().
go_result gomotion::go_pose_scale_mult (const go_pose * p1, go_real s, go_pose * pout)
Definition at line 2559 of file gomath.cpp.
References go_cart_scale_mult(), go_quat_scale_mult(), gomotion::go_pose::rot, and gomotion::go_pose::tran.
Referenced by go_pose_pose_interp().
go_pose gomotion::go_pose_this (go_real x, go_real y, go_real z, go_real rs, go_real rx, go_real ry, go_real rz)
Convenience function that returns a go_pose given individual elements.
Definition at line 905 of file gomath.cpp.
References gomotion::go_pose::rot, gomotion::go_quat::s, gomotion::go_pose::tran, gomotion::go_cart::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_quat::y, gomotion::go_cart::z, and gomotion::go_quat::z.
go_result gomotion::go_pose_vel_mult (const go_pose * pose, const go_vel * vel, go_vel * out)
Given pose transformation from frame A to B, and a velocity vel in frame A, transform the velocity into frame B and place in out.
Definition at line 2617 of file gomath.cpp.
References go_cart_cart_add(), go_cart_cart_cross(), go_pose_inv(), go_quat_cart_mult(), GO_RESULT_OK, gomotion::go_pose::rot, gomotion::go_pose::tran, gomotion::go_vel::v, and gomotion::go_vel::w.
go_result gomotion::go_quadratic_solve (const go_quadratic * quad, go_complex * z1, go_complex * z2)
Definition at line 1583 of file gomath.cpp.
References gomotion::go_quadratic::a, gomotion::go_quadratic::b, GO_RESULT_OK, GO_SMALL, go_sq, gomotion::go_complex::im, and gomotion::go_complex::re.
Referenced by go_cubic_solve(), and go_quartic_solve().
go_result gomotion::go_quartic_solve (const go_quartic * quart, go_complex * z1, go_complex * z2, go_complex * z3, go_complex * z4)
Definition at line 1676 of file gomath.cpp.
References gomotion::go_quadratic::a, gomotion::go_cubic::a, gomotion::go_quartic::a, gomotion::go_quadratic::b, gomotion::go_cubic::b, gomotion::go_quartic::b, gomotion::go_cubic::c, gomotion::go_quartic::c, gomotion::go_quartic::d, go_complex_add(), go_complex_inv(), go_complex_magsq(), go_complex_mult(), go_complex_scale(), go_complex_sqrt(), go_complex_sub(), go_cubic_solve(), go_quadratic_solve(), GO_RESULT_OK, GO_SMALL, go_sq, gocode, gomotion::go_complex::im, and gomotion::go_complex::re.
go_result gomotion::go_quat_cart_mult (const go_quat * q1, const go_cart * v2, go_cart * vout)
Definition at line 2464 of file gomath.cpp.
References go_quat_is_norm(), GO_RESULT_NORM_ERROR, GO_RESULT_OK, gomotion::go_quat::s, gomotion::go_cart::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_quat::y, gomotion::go_cart::z, and gomotion::go_quat::z.
Referenced by go_cart_cart_pose(), go_pose_cart_mult(), go_pose_inv(), go_pose_pose_mult(), go_pose_vel_mult(), go_rpy_cart_mult(), and gomotion::go_motion_queue::interp_world().
go_quat gomotion::go_quat_identity (void)
Returns the identity (zero) quaternion, i.e., no rotation.
Definition at line 925 of file gomath.cpp.
References gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by gomotion::go_motion_queue::append_world().
go_result gomotion::go_quat_inv (const go_quat * q1, go_quat * qout)
Definition at line 2389 of file gomath.cpp.
References go_quat_is_norm(), GO_RESULT_NORM_ERROR, GO_RESULT_OK, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by gomotion::go_motion_queue::append_world(), and go_pose_inv().
go_flag gomotion::go_quat_is_norm (const go_quat * q1)
Definition at line 2403 of file gomath.cpp.
References go_sq, GO_TRAN_CLOSE, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by go_quat_cart_mult(), go_quat_inv(), and go_quat_quat_mult().
go_result gomotion::go_quat_mag (const go_quat * quat, go_real * d)
Definition at line 2335 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by gomotion::go_motion_queue::append_world(), and go_quat_unit().
go_result gomotion::go_quat_mat_convert (const go_quat * q, go_mat * m)
Definition at line 412 of file gomath.cpp.
References GO_RESULT_OK, go_sq, gomotion::go_quat::s, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_quat::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_quat::z.
Referenced by go_pose_hom_convert(), go_quat_matrix_convert(), go_quat_rpy_convert(), go_quat_zyx_convert(), and go_quat_zyz_convert().
go_result gomotion::go_quat_matrix_convert (const go_quat * quat, go_matrix * matrix)
Definition at line 3117 of file gomath.cpp.
References gomotion::go_matrix::cols, gomotion::go_matrix::el, go_mat_matrix_convert(), go_quat_mat_convert(), GO_RESULT_ERROR, GO_RESULT_OK, and gomotion::go_matrix::rows.
go_result gomotion::go_quat_norm (const go_quat * q1, go_quat * qout)
Definition at line 2357 of file gomath.cpp.
References GO_RESULT_NORM_ERROR, GO_RESULT_OK, GO_ROT_SMALL, go_sq, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by go_cart_cart_pose(), and go_mat_quat_convert().
go_flag gomotion::go_quat_quat_compare (const go_quat * q1, const go_quat * q2)
Definition at line 2314 of file gomath.cpp.
References GO_ROT_CLOSE, GO_ROT_SMALL, GO_TRAN_CLOSE, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by go_pose_pose_compare().
go_result gomotion::go_quat_quat_mult (const go_quat * q1, const go_quat * q2, go_quat * qout)
Definition at line 2436 of file gomath.cpp.
References go_quat_is_norm(), GO_RESULT_NORM_ERROR, GO_RESULT_OK, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by gomotion::go_motion_queue::append_world(), go_pose_pose_mult(), and gomotion::go_motion_queue::interp_world().
go_result gomotion::go_quat_rpy_convert (const go_quat * q, go_rpy * rpy)
Definition at line 450 of file gomath.cpp.
References go_mat_rpy_convert(), go_quat_mat_convert(), and GO_RESULT_OK.
Referenced by go_rvec_rpy_convert().
go_result gomotion::go_quat_rvec_convert (const go_quat * q, go_rvec * r)
Definition at line 391 of file gomath.cpp.
References GO_RESULT_OK, GO_ROT_SMALL, go_sq, gomotion::go_quat::s, gomotion::go_rvec::x, gomotion::go_quat::x, gomotion::go_rvec::y, gomotion::go_quat::y, gomotion::go_rvec::z, and gomotion::go_quat::z.
Referenced by go_mat_rvec_convert(), and go_rpy_rvec_convert().
go_result gomotion::go_quat_scale_mult (const go_quat * q, go_real s, go_quat * qout)
Definition at line 2411 of file gomath.cpp.
References GO_RESULT_OK, GO_SMALL, go_sq, gomotion::go_quat::s, gomotion::go_quat::x, gomotion::go_quat::y, and gomotion::go_quat::z.
Referenced by go_pose_scale_mult(), go_quat_unit(), and gomotion::go_motion_queue::interp_world().
go_result gomotion::go_quat_unit (const go_quat * q, go_quat * qout)
go_quat_unit takes a quaternion rotation q and converts it into a unit rotation about the same axis, qout.
Definition at line 2346 of file gomath.cpp.
References go_quat_mag(), go_quat_scale_mult(), GO_RESULT_ERROR, and GO_SMALL.
Referenced by gomotion::go_motion_queue::append_world().
go_result gomotion::go_quat_xyz_convert (const go_quat * , go_xyz *)
go_result gomotion::go_quat_zyx_convert (const go_quat * q, go_zyx * zyx)
Definition at line 440 of file gomath.cpp.
References go_mat_zyx_convert(), go_quat_mat_convert(), and GO_RESULT_OK.
go_result gomotion::go_quat_zyz_convert (const go_quat * q, go_zyz * zyz)
Definition at line 430 of file gomath.cpp.
References go_mat_zyz_convert(), go_quat_mat_convert(), and GO_RESULT_OK.
go_result gomotion::go_rpy_cart_mult (const go_rpy * rpy, const go_cart * in, go_cart * out)
Definition at line 2207 of file gomath.cpp.
References go_quat_cart_mult(), and go_rpy_quat_convert().
go_result gomotion::go_rpy_mat_convert (const go_rpy * rpy, go_mat * m)
Definition at line 829 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_rpy::p, gomotion::go_rpy::r, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_rpy::y, gomotion::go_cart::z, and gomotion::go_mat::z.
Referenced by go_rpy_quat_convert(), go_rpy_zyx_convert(), and go_rpy_zyz_convert().
go_result gomotion::go_rpy_quat_convert (const go_rpy * rpy, go_quat * quat)
Definition at line 819 of file gomath.cpp.
References go_mat_quat_convert(), GO_RESULT_OK, and go_rpy_mat_convert().
Referenced by go_rpy_cart_mult(), and go_rpy_rvec_convert().
go_result gomotion::go_rpy_rvec_convert (const go_rpy * rpy, go_rvec * rvec)
Definition at line 809 of file gomath.cpp.
References go_quat_rvec_convert(), GO_RESULT_OK, and go_rpy_quat_convert().
go_result gomotion::go_rpy_xyz_convert (const go_rpy * , go_xyz *)
go_result gomotion::go_rpy_zyx_convert (const go_rpy * rpy, go_zyx * zyx)
Definition at line 867 of file gomath.cpp.
References go_mat_zyx_convert(), GO_RESULT_OK, and go_rpy_mat_convert().
go_result gomotion::go_rpy_zyz_convert (const go_rpy * rpy, go_zyz * zyz)
Definition at line 857 of file gomath.cpp.
References go_mat_zyz_convert(), GO_RESULT_OK, and go_rpy_mat_convert().
go_result gomotion::go_rvec_cart_convert (const go_rvec * rvec, go_cart * cart)
Definition at line 967 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_rvec::x, gomotion::go_cart::y, gomotion::go_rvec::y, gomotion::go_cart::z, and gomotion::go_rvec::z.
go_result gomotion::go_rvec_mat_convert (const go_rvec * r, go_mat * m)
Definition at line 319 of file gomath.cpp.
References go_cart_mag(), go_cart_unit(), GO_RESULT_OK, go_sincos(), go_sq, gomotion::go_cart::x, gomotion::go_rvec::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_rvec::y, gomotion::go_mat::y, gomotion::go_cart::z, gomotion::go_rvec::z, and gomotion::go_mat::z.
Referenced by go_rvec_zyx_convert(), and go_rvec_zyz_convert().
go_result gomotion::go_rvec_quat_convert (const go_rvec * r, go_quat * q)
Definition at line 283 of file gomath.cpp.
References go_cart_mag(), go_cart_unit(), GO_RESULT_OK, go_sincos(), gomotion::go_quat::s, gomotion::go_cart::x, gomotion::go_rvec::x, gomotion::go_quat::x, gomotion::go_cart::y, gomotion::go_rvec::y, gomotion::go_quat::y, gomotion::go_cart::z, gomotion::go_rvec::z, and gomotion::go_quat::z.
Referenced by gomotion::go_motion_queue::append_world(), go_cart_cart_rot(), go_link_joint_set(), and go_rvec_rpy_convert().
go_result gomotion::go_rvec_rpy_convert (const go_rvec * r, go_rpy * rpy)
Definition at line 380 of file gomath.cpp.
References go_quat_rpy_convert(), GO_RESULT_OK, and go_rvec_quat_convert().
go_flag gomotion::go_rvec_rvec_compare (const go_rvec * r1, const go_rvec * r2)
Definition at line 2187 of file gomath.cpp.
References GO_ROT_CLOSE, gomotion::go_rvec::x, gomotion::go_rvec::y, and gomotion::go_rvec::z.
go_result gomotion::go_rvec_scale_mult (const go_rvec * r, go_real s, go_rvec * rout)
Definition at line 2198 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_rvec::x, gomotion::go_rvec::y, and gomotion::go_rvec::z.
go_result gomotion::go_rvec_xyz_convert (const go_rvec * , go_xyz *)
go_result gomotion::go_rvec_zyx_convert (const go_rvec * rvec, go_zyx * zyx)
Definition at line 369 of file gomath.cpp.
References go_mat_zyx_convert(), GO_RESULT_OK, and go_rvec_mat_convert().
go_result gomotion::go_rvec_zyz_convert (const go_rvec * rvec, go_zyz * zyz)
Definition at line 358 of file gomath.cpp.
References go_mat_zyz_convert(), GO_RESULT_OK, and go_rvec_mat_convert().
go_result gomotion::go_set_singular_epsilon (go_real epsilon)
Definition at line 2985 of file gomath.cpp.
References GO_RESULT_ERROR, and GO_RESULT_OK.
void gomotion::go_sincos (go_real x, go_real * s, go_real * c)
Returns the sine and cosine of x (in radians) in s and c, respectively. Implemented as a single call when supported, to speed up the calculation of the two values.
Definition at line 44 of file gomath.cpp.
References sincos().
Referenced by go_dh_hom_convert(), go_rvec_mat_convert(), go_rvec_quat_convert(), go_sph_cart_convert(), and go_sph_cyl_convert().
go_result gomotion::go_sph_cart_convert (const go_sph * s, go_cart * v)
Definition at line 232 of file gomath.cpp.
References GO_RESULT_OK, go_sincos(), gomotion::go_sph::phi, gomotion::go_sph::r, gomotion::go_sph::theta, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_sph_cyl_convert (const go_sph * s, go_cyl * c)
Definition at line 246 of file gomath.cpp.
References GO_RESULT_OK, go_sincos(), gomotion::go_sph::phi, gomotion::go_sph::r, gomotion::go_cyl::r, gomotion::go_sph::theta, gomotion::go_cyl::theta, and gomotion::go_cyl::z.
go_result gomotion::go_traj_ca_compute (go_real d, go_real v, go_real a, go_traj_ca_spec * pts) inline
go_traj_ca_compute() takes values for distance 'd' to move, max velocity 'v' to limit if necessary, and constant accel 'a', and fills in the go_traj_ca_spec with the interval parameters.
cruise phase
no cruise phase
cruise phase
no cruise phase
Definition at line 230 of file gotraj.h.
References gomotion::go_traj_ca_spec::at0, gomotion::go_traj_ca_spec::dt1, gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_RESULT_ERROR, GO_RESULT_OK, go_sq, gomotion::go_traj_ca_spec::invd, reciprocate, gomotion::go_traj_ca_spec::t1, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, and gomotion::go_traj_ca_spec::vt1.
Referenced by gomotion::go_scale_spec::set().
go_result gomotion::go_traj_ca_extend (const go_traj_ca_spec * ts, go_real t, go_traj_ca_spec * pts) inline
go_traj_ca_extend() takes a time 't' for the desired time to finish the motion, and extends the constant-speed section so that it stops then.
The time must be shorter than the original time, and longer than the fastest stopping time.
Definition at line 366 of file gotraj.h.
References gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_RESULT_OK, gomotion::go_traj_ca_spec::invd, reciprocate, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, and gomotion::go_traj_ca_spec::vt1.
go_result gomotion::go_traj_ca_generate (go_real acc, go_real deltacc, go_real deltvel, go_traj_ca_spec * pts) inline
go_traj_ca_generate() takes an accel value, and intervals for the accel period and cruise period, and fills in the go_traj_ca_spec with the interval parameters.
constant acceleration functions
This is useful for generating test cases.
any time intervals less than 0. mean 0.
compute intermediate values for end of each phase
any time intervals less than 0. mean 0.
compute intermediate values for end of each phase
Definition at line 197 of file gotraj.h.
References gomotion::go_traj_ca_spec::at0, gomotion::go_traj_ca_spec::dt1, gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_RESULT_ERROR, GO_RESULT_OK, go_sq, gomotion::go_traj_ca_spec::invd, reciprocate, gomotion::go_traj_ca_spec::t1, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, and gomotion::go_traj_ca_spec::vt1.
go_result gomotion::go_traj_ca_interp (const go_traj_ca_spec * ts, go_real t, go_traj_interp_spec * ti) inline
go_traj_ca_interp() takes a go_traj_ca_spec and interpolates the d-v-a values for the given time t, storing the d-v-a values in ti.
run interpolation on each phase for each motion parameter, using
d = d0 + v0 t + 1/2 a0 t^2 v = v0 + a0 t a = a0 j = 0
where d0, v0, a0 are the initial values for each phase
Definition at line 400 of file gotraj.h.
References gomotion::go_traj_interp_spec::a, gomotion::go_traj_ca_spec::at0, gomotion::go_traj_interp_spec::d, gomotion::go_traj_ca_spec::dt1, gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_INF, GO_RESULT_OK, go_sq, gomotion::go_traj_ca_spec::invd, gomotion::go_traj_interp_spec::j, gomotion::go_traj_interp_spec::s, gomotion::go_traj_ca_spec::t1, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, gomotion::go_traj_interp_spec::v, and gomotion::go_traj_ca_spec::vt1.
Referenced by gomotion::go_scale_spec::eval().
go_result gomotion::go_traj_ca_scale (const go_traj_ca_spec * ts, go_real t, go_traj_ca_spec * pts) inline
go_traj_ca_scale() takes a time 't' for the desired time of the motion, and scales the times and motion params so that the total distance remains the same and everything else is in proportion
can't shrink motion
this just adds a cruise phase to stretch the time, and reduces
the acc value accordingly
can't shrink motion
this just adds a cruise phase to stretch the time, and reduces
the acc value accordingly
Definition at line 274 of file gotraj.h.
References gomotion::go_traj_ca_spec::at0, gomotion::go_traj_ca_spec::dt1, gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_RESULT_OK, gomotion::go_traj_ca_spec::invd, gomotion::go_traj_ca_spec::t1, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, and gomotion::go_traj_ca_spec::vt1.
go_result gomotion::go_traj_ca_stop (const go_traj_ca_spec * ts, go_real t, go_traj_ca_spec * pts) inline
go_traj_ca_stop() takes a time 't' for the desired time to begin stopping, and recomputes the times so that the move will stop as soon as possible during subsequent interps.
stage I
null stage II, same as I
stage III
stage I unchanged
stage II
stage III
already in stage III, do nothing
stage I
null stage II, same as I
stage III
stage I unchanged
stage II
stage III
already in stage III, do nothing
Definition at line 315 of file gotraj.h.
References gomotion::go_traj_ca_spec::at0, gomotion::go_traj_ca_spec::dt1, gomotion::go_traj_ca_spec::dt2, gomotion::go_traj_ca_spec::dtend, GO_INF, GO_RESULT_OK, go_sq, gomotion::go_traj_ca_spec::invd, reciprocate, gomotion::go_traj_ca_spec::t1, gomotion::go_traj_ca_spec::t2, gomotion::go_traj_ca_spec::tend, and gomotion::go_traj_ca_spec::vt1.
go_result gomotion::go_traj_cj_compute (go_real d, go_real v, go_real a, go_real j, go_traj_cj_spec * pts) inline
go_traj_cj_compute() takes values for distance 'd' to move, max velocity 'v' to limit if necessary, max accel 'a' to limit if necessary, and constant jerk 'j', and fills in the go_traj_cj_spec with the interval parameters.
! Given a total move distance d, maximum peak speed v, maximum peak acceleration a and jerk j, compute the times for each of the seven phases (jerk, accel, dejerk, cruise, dejerk, decel and jerk), and the associated cumulative distances, instantaneous speeds and accelerations.
The resulting structure pts will be used by the constant-jerk interpolater go_traj_cj_interp repeatedly when evaluating the motion along this trajectory.
fill the targets in, and they will be recomputed if needed
accel phase
cruise phase
no cruise phase
no accel phase
cruise phase
no cruise phase
fill the targets in, and they will be recomputed if needed
accel phase
cruise phase
no cruise phase
no accel phase
cruise phase
no cruise phase
Definition at line 621 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dtend, go_cub, GO_RESULT_ERROR, GO_RESULT_OK, go_sq, go_traj_cj_compute_tees_a_c(), go_traj_cj_compute_tees_a_nc(), go_traj_cj_compute_tees_na_c(), go_traj_cj_compute_tees_na_nc(), go_traj_cj_compute_the_rest(), gomotion::go_traj_cj_spec::jt0, and gomotion::go_traj_cj_spec::vt3.
Referenced by gomotion::go_motion_queue::append_joint(), gomotion::go_motion_queue::append_ujoint(), and gomotion::go_motion_queue::append_world().
go_result gomotion::go_traj_cj_compute_tees_a_c (go_traj_cj_spec * pts) inline
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration but a cruise phase, given pts filled in with dtend, jt0, at1 and vt3.
A subsequent call to go_traj_cj_compute_the_rest will fill in the remaining parameters which will be used repeatedly by go_traj_cj_interp.
Definition at line 603 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dtend, GO_RESULT_OK, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t4, and gomotion::go_traj_cj_spec::vt3.
Referenced by go_traj_cj_compute().
go_result gomotion::go_traj_cj_compute_tees_a_nc (go_traj_cj_spec * pts) inline
! Computes the trajectory defining times t1, t2 and t4 for a motion with acceleration but no cruise phase, given pts filled in with dtend, jt0 and at1.
A subsequent call to go_traj_cj_compute_the_rest will fill in the remaining parameters which will be used repeatedly by go_traj_cj_interp.
Definition at line 564 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dtend, GO_RESULT_OK, go_sq, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, and gomotion::go_traj_cj_spec::t4.
Referenced by go_traj_cj_compute().
go_result gomotion::go_traj_cj_compute_tees_na_c (go_traj_cj_spec * pts) inline
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration but a cruise phase, given pts filled in with dtend, jt0 and vt3.
A subsequent call to go_traj_cj_compute_the_rest will fill in the remaining parameters which will be used repeatedly by go_traj_cj_interp.
Definition at line 585 of file gotraj.h.
References gomotion::go_traj_cj_spec::dtend, GO_RESULT_OK, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t4, and gomotion::go_traj_cj_spec::vt3.
Referenced by go_traj_cj_compute().
go_result gomotion::go_traj_cj_compute_tees_na_nc (go_traj_cj_spec * pts) inline
! Computes the trajectory defining times t1, t2 and t4 for a motion with no acceleration or cruise phase, given pts filled in with dtend and jt0.
A subsequent call to go_traj_cj_compute_the_rest will fill in the remaining parameters which will be used repeatedly by go_traj_cj_interp.
Definition at line 546 of file gotraj.h.
References gomotion::go_traj_cj_spec::dtend, go_cbrt(), GO_RESULT_OK, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, and gomotion::go_traj_cj_spec::t4.
Referenced by go_traj_cj_compute().
go_result gomotion::go_traj_cj_compute_the_rest (go_traj_cj_spec * pts) inline
! Expects pts attributes dtend, jt0, at1, vt3, t1, t2 and t3 to be already filled in from previous calls to one of the four go_traj_cj_compute_tees functions and go_traj_cj_compute.
Fills in all the remaining values in pts: the times for each of the seven phases, the associated cumulative distances, and the instantaneous speeds and accelerations.
Definition at line 510 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dt1, gomotion::go_traj_cj_spec::dt2, gomotion::go_traj_cj_spec::dt3, gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, GO_RESULT_OK, gomotion::go_traj_cj_spec::invd, gomotion::go_traj_cj_spec::jt0, reciprocate, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t3, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, gomotion::go_traj_cj_spec::vt1, gomotion::go_traj_cj_spec::vt2, and gomotion::go_traj_cj_spec::vt3.
Referenced by go_traj_cj_compute().
go_result gomotion::go_traj_cj_extend (const go_traj_cj_spec * ts, go_real t, go_traj_cj_spec * pts) inline
go_traj_cj_extend() takes a time 't' for the desired time to finish the motion, and extends the constant-speed section so that it stops then.
The time must be shorter than the original time, and longer than the fastest stopping time.
Definition at line 875 of file gotraj.h.
References gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, GO_RESULT_OK, gomotion::go_traj_cj_spec::invd, reciprocate, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, and gomotion::go_traj_cj_spec::vt3.
Referenced by gomotion::go_motion_queue::stop().
go_result gomotion::go_traj_cj_generate (go_real jrk, go_real deltjrk, go_real deltacc, go_real deltvel, go_traj_cj_spec * pts) inline
go_traj_cj_generate() takes a jerk value, and intervals for the jerk period, accel period and cruise period, and fills in the go_traj_cj_spec with the interval parameters.
constant jerk functions
This is useful for generating test cases.
any time intervals less than 0. mean 0.
compute intermediate values for end of each phase
any time intervals less than 0. mean 0.
compute intermediate values for end of each phase
Definition at line 448 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dt1, gomotion::go_traj_cj_spec::dt2, gomotion::go_traj_cj_spec::dt3, gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, go_cub, GO_RESULT_ERROR, GO_RESULT_OK, go_sq, gomotion::go_traj_cj_spec::invd, gomotion::go_traj_cj_spec::jt0, reciprocate, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t3, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, gomotion::go_traj_cj_spec::vt1, gomotion::go_traj_cj_spec::vt2, and gomotion::go_traj_cj_spec::vt3.
go_result gomotion::go_traj_cj_interp (const go_traj_cj_spec * ts, go_real t, go_traj_interp_spec * ti) inline
go_traj_cj_interp() takes a go_traj_cj_spec and interpolates the d-v-a-j values for the given time t, storing the d-v-a-j values in ti.
run interpolation on each phase for each motion parameter, using
d = d0 + v0 t + 1/2 a0 t^2 + 1/6 j0 t^3 v = v0 + a0 t + 1/2 j0 t^2 a = a0 + j0 t j = j0
where d0, v0, a0, j0 are the initial values for each phase
Definition at line 913 of file gotraj.h.
References gomotion::go_traj_interp_spec::a, gomotion::go_traj_cj_spec::at1, gomotion::go_traj_interp_spec::d, gomotion::go_traj_cj_spec::dt1, gomotion::go_traj_cj_spec::dt2, gomotion::go_traj_cj_spec::dt3, gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, go_cub, GO_INF, GO_RESULT_OK, go_sq, gomotion::go_traj_cj_spec::invd, gomotion::go_traj_interp_spec::j, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_interp_spec::s, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t3, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, gomotion::go_traj_interp_spec::v, gomotion::go_traj_cj_spec::vt1, gomotion::go_traj_cj_spec::vt2, and gomotion::go_traj_cj_spec::vt3.
Referenced by gomotion::go_motion_queue::interp_joint(), and gomotion::go_motion_queue::interp_world().
go_result gomotion::go_traj_cj_scale (const go_traj_cj_spec * ts, go_real t, go_traj_cj_spec * pts) inline
go_traj_cj_scale() takes a time 't' for the desired time of the motion, and scales the times and motion params so that the total distance remains the same and everything else is in proportion
can't shrink shorter
can't shrink shorter
Definition at line 659 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dt1, gomotion::go_traj_cj_spec::dt2, gomotion::go_traj_cj_spec::dt3, gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, go_cub, GO_RESULT_OK, go_sq, gomotion::go_traj_cj_spec::invd, gomotion::go_traj_cj_spec::jt0, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t3, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, gomotion::go_traj_cj_spec::vt1, gomotion::go_traj_cj_spec::vt2, and gomotion::go_traj_cj_spec::vt3.
Referenced by gomotion::go_motion_queue::append_joint(), and gomotion::go_motion_queue::append_world().
go_result gomotion::go_traj_cj_stop (const go_traj_cj_spec * ts, go_real t, go_traj_cj_spec * pts) inline
go_traj_cj_stop() takes a time 't' for the desired time to begin stopping, and recomputes the times so that the move will stop as soon as possible during subsequent interps.
incremental phase II distance
incremental phase III distance
incremental phase IV time
incremental phase IV distance
stopping in stage I
adjust stage I
null stage II, same as I
stage III
null stage IV, same as III
stage V
do earlier
so we can use it here
null stage VI, same as V
stage VII
stopping in stage II
stage I unchanged
adjust stage II
stage III
null stage IV, same as III
stage V
stage VI
stage VII
stopping in stage III
stages I, II and III unchanged
null stage IV
take off original stage IV for remaining stages
stopping in stage IV
stages I, II and III unchanged
adjusted stage IV
stopping in stage V, VI or VII– leave alone
incremental phase II distance
incremental phase III distance
incremental phase IV time
incremental phase IV distance
stopping in stage I
adjust stage I
null stage II, same as I
stage III
null stage IV, same as III
stage V
do earlier
so we can use it here
null stage VI, same as V
stage VII
stopping in stage II
stage I unchanged
adjust stage II
stage III
null stage IV, same as III
stage V
stage VI
stage VII
stopping in stage III
stages I, II and III unchanged
null stage IV
take off original stage IV for remaining stages
stopping in stage IV
stages I, II and III unchanged
adjusted stage IV
stopping in stage V, VI or VII– leave alone
Definition at line 722 of file gotraj.h.
References gomotion::go_traj_cj_spec::at1, gomotion::go_traj_cj_spec::dt1, gomotion::go_traj_cj_spec::dt2, gomotion::go_traj_cj_spec::dt3, gomotion::go_traj_cj_spec::dt4, gomotion::go_traj_cj_spec::dt5, gomotion::go_traj_cj_spec::dt6, gomotion::go_traj_cj_spec::dtend, go_cub, GO_INF, GO_RESULT_OK, go_sq, gomotion::go_traj_cj_spec::invd, gomotion::go_traj_cj_spec::jt0, reciprocate, gomotion::go_traj_cj_spec::t1, gomotion::go_traj_cj_spec::t2, gomotion::go_traj_cj_spec::t3, gomotion::go_traj_cj_spec::t4, gomotion::go_traj_cj_spec::t5, gomotion::go_traj_cj_spec::t6, gomotion::go_traj_cj_spec::tend, gomotion::go_traj_cj_spec::vt1, gomotion::go_traj_cj_spec::vt2, and gomotion::go_traj_cj_spec::vt3.
Referenced by gomotion::go_motion_queue::stop().
go_result gomotion::go_tridiag_ql (go_real * d, go_real * e, go_integer n, go_real ** z)
This computes the eigenvalues and eigenvectors of the tridiagonalized matrix with diagonal d and off-diagonal e, using QL reduction with implicit shifts. d, e and z should have been generated by a prior call to go_tridiag_reduce. d will contain the eigenvalues, and z will contain the eigenvectors.
Calling example:
go_tridiag_reduce(matrix, 3, d, e); go_tridiag_ql(d, e, 3, matrix);
d will contain the eigenvalues of the original matrix, and the new matrix will contain the eigenvectors.
Definition at line 1957 of file gomath.cpp.
References GO_RESULT_ERROR, GO_RESULT_OK, MAG2, and SIGN.
Referenced by go_cart_cart_pose().
go_result gomotion::go_tridiag_reduce (go_real ** a, go_integer n, go_real * d, go_real * e)
This computes the Householder reduction to tridiagonal form of a real symmetric matrix a. a will contain the orthogonal matrix that effects the transformation. d will contain the diagonal elements, and e will contain the off-diagonal elements. This is used by go_tridiag_ql to find the eigenvalues and eigenvectors of a real symmetric matrix.
Definition at line 1867 of file gomath.cpp.
References GO_RESULT_OK.
Referenced by go_cart_cart_pose().
go_result gomotion::go_uxz_mat_convert (const go_uxz * uxz, go_mat * mat)
Definition at line 877 of file gomath.cpp.
References go_cart_cart_cross(), go_cart_cart_proj(), go_cart_cart_sub(), go_cart_unit(), GO_RESULT_OK, gomotion::go_mat::x, gomotion::go_uxz::x, gomotion::go_mat::y, gomotion::go_mat::z, and gomotion::go_uxz::z.
go_result gomotion::go_vector_cart_convert (const go_real * v, go_cart * c)
Definition at line 3109 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_cart::y, and gomotion::go_cart::z.
go_result gomotion::go_xyz_mat_convert (const go_xyz * xyz, go_mat * m)
Definition at line 777 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_xyz::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_xyz::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_xyz::z.
go_result gomotion::go_xyz_quat_convert (const go_xyz * , go_quat *)
go_result gomotion::go_xyz_rpy_convert (const go_xyz * , go_rpy *)
go_result gomotion::go_xyz_rvec_convert (const go_xyz * , go_rvec *)
go_result gomotion::go_xyz_zyx_convert (const go_xyz * , go_zyx *)
go_result gomotion::go_xyz_zyz_convert (const go_xyz * , go_zyz *)
go_result gomotion::go_zyx_mat_convert (const go_zyx * zyx, go_mat * m)
Definition at line 729 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_zyx::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_zyx::y, gomotion::go_cart::z, gomotion::go_mat::z, and gomotion::go_zyx::z.
Referenced by go_zyx_quat_convert(), go_zyx_rpy_convert(), go_zyx_rvec_convert(), and go_zyx_zyz_convert().
go_result gomotion::go_zyx_quat_convert (const go_zyx * zyx, go_quat * q)
Definition at line 718 of file gomath.cpp.
References go_mat_quat_convert(), GO_RESULT_OK, and go_zyx_mat_convert().
go_result gomotion::go_zyx_rpy_convert (const go_zyx * zyx, go_rpy * rpy)
Definition at line 767 of file gomath.cpp.
References go_mat_rpy_convert(), GO_RESULT_OK, and go_zyx_mat_convert().
go_result gomotion::go_zyx_rvec_convert (const go_zyx * zyx, go_rvec * r)
Definition at line 706 of file gomath.cpp.
References go_mat_rvec_convert(), GO_RESULT_OK, and go_zyx_mat_convert().
go_result gomotion::go_zyx_xyz_convert (const go_zyx * , go_xyz *)
go_result gomotion::go_zyx_zyz_convert (const go_zyx * zyx, go_zyz * zyz)
Definition at line 757 of file gomath.cpp.
References go_mat_zyz_convert(), GO_RESULT_OK, and go_zyx_mat_convert().
go_result gomotion::go_zyz_mat_convert (const go_zyz * zyz, go_mat * m)
Definition at line 657 of file gomath.cpp.
References GO_RESULT_OK, gomotion::go_cart::x, gomotion::go_mat::x, gomotion::go_cart::y, gomotion::go_mat::y, gomotion::go_zyz::y, gomotion::go_cart::z, gomotion::go_mat::z, gomotion::go_zyz::z, and gomotion::go_zyz::zp.
Referenced by go_zyz_quat_convert(), go_zyz_rpy_convert(), go_zyz_rvec_convert(), and go_zyz_zyx_convert().
go_result gomotion::go_zyz_quat_convert (const go_zyz * zyz, go_quat * q)
Definition at line 647 of file gomath.cpp.
References go_mat_quat_convert(), GO_RESULT_OK, and go_zyz_mat_convert().
go_result gomotion::go_zyz_rpy_convert (const go_zyz * zyz, go_rpy * rpy)
Definition at line 695 of file gomath.cpp.
References go_mat_rpy_convert(), GO_RESULT_OK, and go_zyz_mat_convert().
go_result gomotion::go_zyz_rvec_convert (const go_zyz * zyz, go_rvec * r)
Definition at line 637 of file gomath.cpp.
References go_mat_rvec_convert(), GO_RESULT_OK, and go_zyz_mat_convert().
go_result gomotion::go_zyz_xyz_convert (const go_zyz * , go_xyz *)
go_result gomotion::go_zyz_zyx_convert (const go_zyz * zyz, go_zyx * zyx)
Definition at line 685 of file gomath.cpp.
References go_mat_zyx_convert(), GO_RESULT_OK, and go_zyz_mat_convert().
go_result gomotion::lubksb (go_real ** a, go_integer n, go_integer * indx, go_real * b)
Definition at line 3070 of file gomath.cpp.
References GO_RESULT_OK, and GO_RESULT_SINGULAR.
Referenced by go_mat6_inv(), and go_matrix_inv().
go_result gomotion::ludcmp (go_real ** a, go_real * scratchrow, go_integer n, go_integer * indx, go_real * d)
Definition at line 2994 of file gomath.cpp.
References GO_RESULT_OK, and GO_RESULT_SINGULAR.
Referenced by go_mat6_inv(), and go_matrix_inv().
void gomotion::sincos (double x, double * sx, double * cx)
Definition at line 31 of file gomath.cpp.
Referenced by go_sincos().