.TH "ArmKinematics" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmKinematics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Kinematics\&.h>\fP
.PP
Inherits \fBIKinematics\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArmKinematics\fP (std::string \fBprefix\fP, tf::Pose \fBbaseoffset\fP)"
.br
.ti -1c
.RI "virtual \fBRCS::Pose\fP \fBFK\fP (std::vector< double > jv)"
.br
.RI "\fIFK performs the forward kinematics using the joint values of the robot provided\&. \fP"
.ti -1c
.RI "virtual std::vector< double > \fBIK\fP (\fBRCS::Pose\fP &pose, std::vector< double > oldjoints)"
.br
.RI "\fIIK performs the inverse kinematics using the Cartesian pose provided\&. \fP"
.ti -1c
.RI "virtual size_t \fBAllPoseToJoints\fP (\fBRCS::Pose\fP &pose, std::vector< std::vector< double > > &newjoints)"
.br
.RI "\fIAllPoseToJoints solves the inverse kinematics to find all solutions using the Cartesian pose provided\&. \fP"
.ti -1c
.RI "virtual std::vector< double > \fBNearestJoints\fP (std::vector< double > oldjoints, std::vector< std::vector< double > > &newjoints)"
.br
.RI "\fINearestJoints finds the joint set that is closest to the old joints\&. \fP"
.ti -1c
.RI "virtual bool \fBIsSingular\fP (\fBRCS::Pose\fP &pose, double threshold)"
.br
.RI "\fIReturns true if the determinant of the jacobian is near zero\&. \&. \fP"
.ti -1c
.RI "virtual void \fBInit\fP (ros::NodeHandle &nh)"
.br
.RI "\fIInitialize kinematics using robot_description to fill parameters \&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArmKinematics::ArmKinematics (std::stringprefix, tf::Posebaseoffset)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual size_t ArmKinematics::AllPoseToJoints (\fBRCS::Pose\fP &pose, std::vector< std::vector< double > > &newjoints)\fC [inline]\fP, \fC [virtual]\fP"

.PP
AllPoseToJoints solves the inverse kinematics to find all solutions using the Cartesian pose provided\&. 
.PP
\fBParameters:\fP
.RS 4
\fICartesian\fP robot pose of end effector\&. 
.br
\fIvector\fP of double vectos to hold all the IK joint solutions\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
number of solutions found\&. 
.RE
.PP

.PP
Implements \fBIKinematics\fP\&.
.SS "virtual \fBRCS::Pose\fP ArmKinematics::FK (std::vector< double >jv)\fC [inline]\fP, \fC [virtual]\fP"

.PP
FK performs the forward kinematics using the joint values of the robot provided\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvector\fP of all robot joint values in doubles\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
corresponding Cartesian robot pose of end effector\&. 
.RE
.PP

.PP
Implements \fBIKinematics\fP\&.
.SS "virtual std::vector<double> ArmKinematics::IK (\fBRCS::Pose\fP &pose, std::vector< double >oldjoints)\fC [inline]\fP, \fC [virtual]\fP"

.PP
IK performs the inverse kinematics using the Cartesian pose provided\&. 
.PP
\fBParameters:\fP
.RS 4
\fICartesian\fP robot pose of end effector\&. 
.br
\fIoptional\fP seed joint values to use as best guess for IK joint values\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
vector of all robot joint values in doubles\&. 
.RE
.PP

.PP
Implements \fBIKinematics\fP\&.
.SS "virtual void ArmKinematics::Init (ros::NodeHandle &nh)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Initialize kinematics using robot_description to fill parameters \&. 
.PP
\fBParameters:\fP
.RS 4
\fInh\fP ros node handle of node\&. 
.RE
.PP

.PP
Reimplemented from \fBIKinematics\fP\&.
.SS "virtual bool ArmKinematics::IsSingular (\fBRCS::Pose\fP &pose, doublethreshold)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Returns true if the determinant of the jacobian is near zero\&. \&. 
.PP
\fBParameters:\fP
.RS 4
\fIgroupname\fP name of chained joints in robot model\&. 
.br
\fIeelinkname\fP name of end effector joint in robot model\&. 
.RE
.PP

.PP
Reimplemented from \fBIKinematics\fP\&.
.SS "virtual std::vector<double> ArmKinematics::NearestJoints (std::vector< double >oldjoints, std::vector< std::vector< double > > &newjoints)\fC [inline]\fP, \fC [virtual]\fP"

.PP
NearestJoints finds the joint set that is closest to the old joints\&. 
.PP
\fBParameters:\fP
.RS 4
\fIold\fP seed joint values to use as best guess for IK joint values\&. 
.br
\fIvector\fP of double vectos that holds all the IK joint solutions\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
vector of doubles with closest set to seed joints\&. 
.RE
.PP

.PP
Implements \fBIKinematics\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
