.TH "Checkers" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checkers \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMove\fP"
.br
.ti -1c
.RI "struct \fBBoardType\fP"
.br
.ti -1c
.RI "struct \fBCheckersGame\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBStrFormat\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string Checkers::StrFormat (const char *fmt, \&.\&.\&.)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
