.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Checkers.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Checkers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCheckers::Move\fP"
.br
.ti -1c
.RI "struct \fBCheckers::BoardType\fP"
.br
.ti -1c
.RI "struct \fBCheckers::CheckersGame\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBCheckers\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROWS\fP   8"
.br
.ti -1c
.RI "#define \fBCOLS\fP   8"
.br
.ti -1c
.RI "#define \fBMAX_DEPTH\fP   50"
.br
.ti -1c
.RI "#define \fBISRED\fP(c)   ( (c & Checkers::RED) >0)"
.br
.ti -1c
.RI "#define \fBISBLACK\fP(c)   ((c & Checkers::BLACK) >0)"
.br
.ti -1c
.RI "#define \fBISEMPTY\fP(c)   (c == Checkers::EMPTY)"
.br
.ti -1c
.RI "#define \fBISKING\fP(c)   ( (c & Checkers::KING) >0)"
.br
.ti -1c
.RI "#define \fBSIGN\fP(x)   (x < 0) ? -1 : (x > 0)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBCheckers::StrFormat\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLS   8"

.SS "#define ISBLACK(c)   ((c & Checkers::BLACK) >0)"

.SS "#define ISEMPTY(c)   (c == Checkers::EMPTY)"

.SS "#define ISKING(c)   ( (c & Checkers::KING) >0)"

.SS "#define ISRED(c)   ( (c & Checkers::RED) >0)"

.SS "#define MAX_DEPTH   50"

.SS "#define ROWS   8"

.SS "#define SIGN(x)   (x < 0) ? -1 : (x > 0)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
