.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Controller.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Controller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <list>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <ros/package\&.h>\fP
.br
\fC#include 'NIST/RCSThreadTemplate\&.h'\fP
.br
\fC#include 'NIST/RCSMsgQueue\&.h'\fP
.br
\fC#include 'NIST/BLogging\&.h'\fP
.br
\fC#include 'nist_fanuc/RCS\&.h'\fP
.br
\fC#include 'nist_fanuc/Gripper\&.h'\fP
.br
\fC#include 'nist_fanuc/Communication\&.h'\fP
.br
\fC#include 'nist_fanuc/RvizMarker\&.h'\fP
.br
\fC#include 'nist_fanuc/Kinematics\&.h'\fP
.br
\fC#include 'nist_fanuc/CsvLogging\&.h'\fP
.br
\fC#include 'nistcrcl/CrclCommandMsg\&.h'\fP
.br
\fC#include 'nistcrcl/CrclStatusMsg\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRCS::CController\fP"
.br
.RI "\fIThe \fBCController\fP provides a collection for all the relevant controller pieces\&. The \fBCController\fP is the main controller class to collect all the references/pointers to instances in the project\&. A global instance of this class, called 'Controller', is created and is used throughout the code to reference various instances of control objects (e\&.g\&., kinematics, joint writer, joint reader, etc\&.) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
