.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Debug.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Debug.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'RCS\&.h'\fP
.br
\fC#include 'Conversions\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::string \fBRCS::VectorDump\fP (std::vector< T > v)"
.br
.ti -1c
.RI "std::string \fBRCS::DumpPose\fP (\fBRCS::Pose\fP &pose)"
.br
.RI "\fIDumpPose takes a urdf pose and generates a string describing pose\&. Can be used as std::cout << DumpPose(pose);\&. \fP"
.ti -1c
.RI "std::string \fBRCS::DumpEigenPose\fP (Eigen::Affine3d pose)"
.br
.ti -1c
.RI "std::string \fBRCS::DumpPoseSimple\fP (\fBRCS::Pose\fP pose)"
.br
.ti -1c
.RI "std::string \fBRCS::DumpJoints\fP (\fBJointState\fP joints)"
.br
.RI "\fIDumpJoints takes a list of joints and generates a string describing pose\&. Can be used as std::cout << DumpPose(pose);\&. \fP"
.ti -1c
.RI "std::ostream & \fBRCS::operator<<\fP (std::ostream &os, \fBRCS::Pose\fP &pose)"
.br
.RI "\fIDumpPose takes a urdf pose and generates a string describing pose\&. Can be used as std::cout << DumpPose(pose);\&. \fP"
.ti -1c
.RI "std::string \fBRCS::DumpQuaterion\fP (std::ostream &os, const \fBRCS::Rotation\fP &rot)"
.br
.RI "\fIDumpQuaterion takes a urdf quaterion and generates a string describing x,y,z,w coordinates\&. Can be used as std::cout << DumpQuaterion(urdf::rotation);\&. \fP"
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRCS::CanonCmd\fP &cc)"
.br
.ti -1c
.RI "template<typename T > std::string \fBMapDump\fP (std::map< std::string, T > m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > std::string MapDump (std::map< std::string, T >m)\fC [inline]\fP"

.SS "std::ostream& operator<< (std::ostream &os, const \fBRCS::CanonCmd\fP &cc)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
