.TH "fanuc_lrmate200id_kin_struct" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fanuc_lrmate200id_kin_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fanuc_lrmate200id\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBthree21_kin\fP \fBtk\fP"
.br
.ti -1c
.RI "tf::Pose \fBt7\fP"
.br
.ti -1c
.RI "tf::Pose \fBt7_inv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tf::Pose fanuc_lrmate200id_kin_struct::t7"

.SS "tf::Pose fanuc_lrmate200id_kin_struct::t7_inv"

.SS "\fBthree21_kin\fP fanuc_lrmate200id_kin_struct::tk"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
