.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/fanuc_lrmate200id.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/fanuc_lrmate200id.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RCS\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBthree21_kin\fP"
.br
.ti -1c
.RI "struct \fBfanuc_lrmate200id_kin_struct\fP"
.br
.ti -1c
.RI "class \fBfanuc_lrmate200id\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWRIST_OFFSET\fP   0\&.080 /*  nominal offset in -Z for wrist */"
.br
.ti -1c
.RI "#define \fBTHREE21_KIN_NUM_JOINTS\fP   6"
.br
.ti -1c
.RI "#define \fBTHREE21_SHOULDER_RIGHT\fP   0x01"
.br
.ti -1c
.RI "#define \fBTHREE21_ELBOW_DOWN\fP   0x02"
.br
.ti -1c
.RI "#define \fBTHREE21_WRIST_FLIP\fP   0x04"
.br
.ti -1c
.RI "#define \fBTHREE21_SINGULAR\fP   0x08"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define THREE21_ELBOW_DOWN   0x02"

.SS "#define THREE21_KIN_NUM_JOINTS   6"

.SS "#define THREE21_SHOULDER_RIGHT   0x01"

.SS "#define THREE21_SINGULAR   0x08"

.SS "#define THREE21_WRIST_FLIP   0x04"

.SS "#define WRIST_OFFSET   0\&.080 /*  nominal offset in -Z for wrist */"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
