.TH "FanucLRmate200iD" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FanucLRmate200iD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Kinematics\&.h>\fP
.PP
Inherits \fBIArmConfiguration\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFanucLRmate200iD\fP ()"
.br
.ti -1c
.RI "virtual void \fBConfigure\fP (int config, size_t size, std::vector< double > &min, std::vector< double > &max)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FanucLRmate200iD::FanucLRmate200iD ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void FanucLRmate200iD::Configure (intconfig, size_tsize, std::vector< double > &min, std::vector< double > &max)\fC [virtual]\fP"

.PP
Reimplemented from \fBIArmConfiguration\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
