.TH "ikfast::IkSolutionList< T >" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ikfast::IkSolutionList< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ikfast\&.h>\fP
.PP
Inherits \fBikfast::IkSolutionListBase< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual size_t \fBAddSolution\fP (const std::vector< \fBIkSingleDOFSolutionBase\fP< T > > &vinfos, const std::vector< int > &vfree)"
.br
.ti -1c
.RI "virtual const \fBIkSolutionBase\fP< T > & \fBGetSolution\fP (size_t index) const "
.br
.ti -1c
.RI "virtual size_t \fBGetNumSolutions\fP () const "
.br
.ti -1c
.RI "virtual void \fBClear\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBIkSolution\fP< T > > \fB_listsolutions\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual size_t \fBikfast::IkSolutionList\fP< T >::AddSolution (const std::vector< \fBIkSingleDOFSolutionBase\fP< T > > &vinfos, const std::vector< int > &vfree)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBikfast::IkSolutionListBase< T >\fP\&.
.SS "template<typename T> virtual void \fBikfast::IkSolutionList\fP< T >::Clear ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBikfast::IkSolutionListBase< T >\fP\&.
.SS "template<typename T> virtual size_t \fBikfast::IkSolutionList\fP< T >::GetNumSolutions () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBikfast::IkSolutionListBase< T >\fP\&.
.SS "template<typename T> virtual const \fBIkSolutionBase\fP<T>& \fBikfast::IkSolutionList\fP< T >::GetSolution (size_tindex) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBikfast::IkSolutionListBase< T >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> std::list<\fBIkSolution\fP<T> > \fBikfast::IkSolutionList\fP< T >::_listsolutions\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
