.TH "IKSolver" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IKSolver \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBComputeIk\fP (const \fBIkReal\fP *eetrans, const \fBIkReal\fP *eerot, const \fBIkReal\fP *pfree, \fBIkSolutionListBase\fP< \fBIkReal\fP > &solutions)"
.br
.ti -1c
.RI "void \fBrotationfunction0\fP (\fBIkSolutionListBase\fP< \fBIkReal\fP > &solutions)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIkReal\fP \fBj0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBj1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBj2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBj3\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj3\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj3\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj3\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBj4\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj4\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj4\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj4\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBj5\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBcj5\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBsj5\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBhtj5\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r00\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr00\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp0_0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r01\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr01\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp0_1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r02\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr02\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp0_2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r10\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr10\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp1_0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r11\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr11\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp1_1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r12\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr12\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp1_2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r20\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr20\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp2_0\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r21\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr21\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp2_1\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_r22\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBr22\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBrxp2_2\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_px\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBpx\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnpx\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_py\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBpy\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnpy\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnew_pz\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBpz\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBnpz\fP"
.br
.ti -1c
.RI "\fBIkReal\fP \fBpp\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij0\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj0\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij1\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj1\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij2\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj2\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij3\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj3\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij4\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj4\fP"
.br
.ti -1c
.RI "unsigned char \fB_ij5\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_nj5\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool IKSolver::ComputeIk (const \fBIkReal\fP *eetrans, const \fBIkReal\fP *eerot, const \fBIkReal\fP *pfree, \fBIkSolutionListBase\fP< \fBIkReal\fP > &solutions)\fC [inline]\fP"

.SS "void IKSolver::rotationfunction0 (\fBIkSolutionListBase\fP< \fBIkReal\fP > &solutions)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char IKSolver::_ij0[2]"

.SS "unsigned char IKSolver::_ij1[2]"

.SS "unsigned char IKSolver::_ij2[2]"

.SS "unsigned char IKSolver::_ij3[2]"

.SS "unsigned char IKSolver::_ij4[2]"

.SS "unsigned char IKSolver::_ij5[2]"

.SS "unsigned char IKSolver::_nj0"

.SS "unsigned char IKSolver::_nj1"

.SS "unsigned char IKSolver::_nj2"

.SS "unsigned char IKSolver::_nj3"

.SS "unsigned char IKSolver::_nj4"

.SS "unsigned char IKSolver::_nj5"

.SS "\fBIkReal\fP IKSolver::cj0"

.SS "\fBIkReal\fP IKSolver::cj1"

.SS "\fBIkReal\fP IKSolver::cj2"

.SS "\fBIkReal\fP IKSolver::cj3"

.SS "\fBIkReal\fP IKSolver::cj4"

.SS "\fBIkReal\fP IKSolver::cj5"

.SS "\fBIkReal\fP IKSolver::htj0"

.SS "\fBIkReal\fP IKSolver::htj1"

.SS "\fBIkReal\fP IKSolver::htj2"

.SS "\fBIkReal\fP IKSolver::htj3"

.SS "\fBIkReal\fP IKSolver::htj4"

.SS "\fBIkReal\fP IKSolver::htj5"

.SS "\fBIkReal\fP IKSolver::j0"

.SS "\fBIkReal\fP IKSolver::j1"

.SS "\fBIkReal\fP IKSolver::j2"

.SS "\fBIkReal\fP IKSolver::j3"

.SS "\fBIkReal\fP IKSolver::j4"

.SS "\fBIkReal\fP IKSolver::j5"

.SS "\fBIkReal\fP IKSolver::new_px"

.SS "\fBIkReal\fP IKSolver::new_py"

.SS "\fBIkReal\fP IKSolver::new_pz"

.SS "\fBIkReal\fP IKSolver::new_r00"

.SS "\fBIkReal\fP IKSolver::new_r01"

.SS "\fBIkReal\fP IKSolver::new_r02"

.SS "\fBIkReal\fP IKSolver::new_r10"

.SS "\fBIkReal\fP IKSolver::new_r11"

.SS "\fBIkReal\fP IKSolver::new_r12"

.SS "\fBIkReal\fP IKSolver::new_r20"

.SS "\fBIkReal\fP IKSolver::new_r21"

.SS "\fBIkReal\fP IKSolver::new_r22"

.SS "\fBIkReal\fP IKSolver::npx"

.SS "\fBIkReal\fP IKSolver::npy"

.SS "\fBIkReal\fP IKSolver::npz"

.SS "\fBIkReal\fP IKSolver::pp"

.SS "\fBIkReal\fP IKSolver::px"

.SS "\fBIkReal\fP IKSolver::py"

.SS "\fBIkReal\fP IKSolver::pz"

.SS "\fBIkReal\fP IKSolver::r00"

.SS "\fBIkReal\fP IKSolver::r01"

.SS "\fBIkReal\fP IKSolver::r02"

.SS "\fBIkReal\fP IKSolver::r10"

.SS "\fBIkReal\fP IKSolver::r11"

.SS "\fBIkReal\fP IKSolver::r12"

.SS "\fBIkReal\fP IKSolver::r20"

.SS "\fBIkReal\fP IKSolver::r21"

.SS "\fBIkReal\fP IKSolver::r22"

.SS "\fBIkReal\fP IKSolver::rxp0_0"

.SS "\fBIkReal\fP IKSolver::rxp0_1"

.SS "\fBIkReal\fP IKSolver::rxp0_2"

.SS "\fBIkReal\fP IKSolver::rxp1_0"

.SS "\fBIkReal\fP IKSolver::rxp1_1"

.SS "\fBIkReal\fP IKSolver::rxp1_2"

.SS "\fBIkReal\fP IKSolver::rxp2_0"

.SS "\fBIkReal\fP IKSolver::rxp2_1"

.SS "\fBIkReal\fP IKSolver::rxp2_2"

.SS "\fBIkReal\fP IKSolver::sj0"

.SS "\fBIkReal\fP IKSolver::sj1"

.SS "\fBIkReal\fP IKSolver::sj2"

.SS "\fBIkReal\fP IKSolver::sj3"

.SS "\fBIkReal\fP IKSolver::sj4"

.SS "\fBIkReal\fP IKSolver::sj5"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
