.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Kinematics.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/Kinematics.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <boost/thread/mutex\&.hpp>\fP
.br
\fC#include 'arm_kinematics\&.h'\fP
.br
\fC#include 'RCS\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Conversions\&.h'\fP
.br
\fC#include 'Debug\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <moveit_msgs/GetPositionFK\&.h>\fP
.br
\fC#include <moveit_msgs/GetPositionIK\&.h>\fP
.br
\fC#include <moveit_msgs/GetKinematicSolverInfo\&.h>\fP
.br
\fC#include <moveit_msgs/KinematicSolverInfo\&.h>\fP
.br
\fC#include 'ikfast\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'fanuc_lrmate200id\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIArmConfiguration\fP"
.br
.ti -1c
.RI "class \fBFanucLRmate200iD\fP"
.br
.ti -1c
.RI "class \fBIKinematics\fP"
.br
.RI "\fIThe \fBIKinematics\fP provides is an abstract class with pure virtual functions that are overriden by actual kinematic implementations\&. \fP"
.ti -1c
.RI "class \fBArmKinematics\fP"
.br
.ti -1c
.RI "class \fBFastKinematics\fP"
.br
.ti -1c
.RI "class \fBFanucLrMate200idKinematics\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr
.br
< \fBIKinematics\fP > \fBIKinematicsSharedPtr\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.SH "Typedef Documentation"
.PP 
.SS "typedef boost::shared_ptr<\fBIKinematics\fP> \fBIKinematicsSharedPtr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
