.TH "MotomanNearestJointsLookup" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MotomanNearestJointsLookup \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Demo\&.h>\fP
.PP
Inherits \fBNearestJointsLookup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotomanNearestJointsLookup\fP (tf::Pose baseoffset, \fBIKinematicsSharedPtr\fP kin)"
.br
.ti -1c
.RI "virtual void \fBSetRobotHints\fP ()"
.br
.RI "\fIEither ik or more trajectory control with spacing between joint updates small so KDL happy\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MotomanNearestJointsLookup::MotomanNearestJointsLookup (tf::Posebaseoffset, \fBIKinematicsSharedPtr\fPkin)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void MotomanNearestJointsLookup::SetRobotHints ()\fC [virtual]\fP"

.PP
Either ik or more trajectory control with spacing between joint updates small so KDL happy\&. 
.PP
Reimplemented from \fBNearestJointsLookup\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
