.TH "NearestJointsLookup::cmp_op" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NearestJointsLookup::cmp_op \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Demo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const tf::Pose &a, const tf::Pose &b)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool NearestJointsLookup::cmp_op::operator() (const tf::Pose &a, const tf::Pose &b)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
