.TH "ObjectDB" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectDB\fP (std::string \fBname\fP, std::string \fBmetatype\fP, std::size_t \fBid\fP)"
.br
.ti -1c
.RI "\fBObjectDB\fP (std::string \fBname\fP, std::string \fBmetatype\fP, std::size_t \fBid\fP, Eigen::Affine3d \fBpose\fP, std::string \fBfilepath\fP, rviz_visual_tools::colors \fBcolor\fP=rviz_visual_tools::CLEAR, double \fBscale\fP=1\&.0)"
.br
.ti -1c
.RI "\fBObjectDB\fP (std::string \fBname\fP, std::string \fBmetatype\fP, Eigen::Affine3d \fBpose\fP=Eigen::Affine3d::Identity(), Eigen::Affine3d \fBadjacentpose\fP=Eigen::Affine3d::Identity(), rviz_visual_tools::colors \fBcolor\fP=rviz_visual_tools::CLEAR)"
.br
.ti -1c
.RI "\fBObjectDB\fP (std::string \fBname\fP, std::string \fBmetatype\fP, Eigen::Affine3d \fBpose\fP, rviz_visual_tools::colors \fBcolor\fP, double \fBheight\fP=0\&.01, double \fBradius\fP=0\&.005, const std::string &ns='Cylinder')"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSave\fP (\fBObjectDB\fP *obj)"
.br
.ti -1c
.RI "static \fBObjectDB\fP * \fBFind\fP (std::size_t \fBid\fP)"
.br
.ti -1c
.RI "static Eigen::Affine3d & \fBFindPose\fP (std::string \fBname\fP)"
.br
.ti -1c
.RI "static \fBObjectDB\fP * \fBFind\fP (std::string \fBname\fP)"
.br
.ti -1c
.RI "static std::string \fBDumpDB\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Eigen::Affine3d \fBpose\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBmetatype\fP"
.br
.ti -1c
.RI "std::string \fBfilepath\fP"
.br
.ti -1c
.RI "rviz_visual_tools::colors \fBcolor\fP"
.br
.ti -1c
.RI "double \fBscale\fP"
.br
.ti -1c
.RI "std::size_t \fBid\fP"
.br
.ti -1c
.RI "rviz_visual_tools::colors \fBfirstcolor\fP"
.br
.ti -1c
.RI "Eigen::Affine3d \fBgrippedpose\fP"
.br
.ti -1c
.RI "double \fBgripperclose\fP"
.br
.ti -1c
.RI "Eigen::Affine3d \fBadjacentpose\fP"
.br
.ti -1c
.RI "Eigen::Vector3d \fBcentroid\fP"
.br
.ti -1c
.RI "double \fBheight\fP"
.br
.ti -1c
.RI "double \fBradius\fP"
.br
.ti -1c
.RI "bool \fBKing\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::map< std::string, 
.br
std::string > \fB_typemapping\fP"
.br
.ti -1c
.RI "static std::size_t \fBgid\fP = 1"
.br
.ti -1c
.RI "static std::vector< \fBObjectDB\fP * > \fBobjects\fP"
.br
.ti -1c
.RI "static \fBObjectDB\fP * \fBdummy\fP = new \fBObjectDB\fP('dummy', 'nevermatch', (std::size_t) 0)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ObjectDB::ObjectDB (std::stringname, std::stringmetatype, std::size_tid)\fC [inline]\fP"

.SS "ObjectDB::ObjectDB (std::stringname, std::stringmetatype, std::size_tid, Eigen::Affine3dpose, std::stringfilepath, rviz_visual_tools::colorscolor = \fCrviz_visual_tools::CLEAR\fP, doublescale = \fC1\&.0\fP)\fC [inline]\fP"

.SS "ObjectDB::ObjectDB (std::stringname, std::stringmetatype, Eigen::Affine3dpose = \fCEigen::Affine3d::Identity()\fP, Eigen::Affine3dadjacentpose = \fCEigen::Affine3d::Identity()\fP, rviz_visual_tools::colorscolor = \fCrviz_visual_tools::CLEAR\fP)\fC [inline]\fP"

.SS "ObjectDB::ObjectDB (std::stringname, std::stringmetatype, Eigen::Affine3dpose, rviz_visual_tools::colorscolor, doubleheight = \fC0\&.01\fP, doubleradius = \fC0\&.005\fP, const std::string &ns = \fC'Cylinder'\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static std::string ObjectDB::DumpDB ()\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBObjectDB\fP* ObjectDB::Find (std::size_tid)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBObjectDB\fP* ObjectDB::Find (std::stringname)\fC [inline]\fP, \fC [static]\fP"

.SS "static Eigen::Affine3d& ObjectDB::FindPose (std::stringname)\fC [inline]\fP, \fC [static]\fP"

.SS "static void ObjectDB::Save (\fBObjectDB\fP *obj)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::map< std::string, std::string > ObjectDB::_typemapping\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        map_list_of("bolt", "mesh")
("boltholder", "mesh")
("wall", "cuboid")
("Checkerboard", "cuboid")
("Cylinder", "Cylinder")
.fi
.SS "Eigen::Affine3d ObjectDB::adjacentpose"

.SS "Eigen::Vector3d ObjectDB::centroid"

.SS "rviz_visual_tools::colors ObjectDB::color"

.SS "\fBObjectDB\fP * ObjectDB::dummy = new \fBObjectDB\fP('dummy', 'nevermatch', (std::size_t) 0)\fC [static]\fP"

.SS "std::string ObjectDB::filepath"

.SS "rviz_visual_tools::colors ObjectDB::firstcolor"

.SS "std::size_t ObjectDB::gid = 1\fC [static]\fP"

.SS "Eigen::Affine3d ObjectDB::grippedpose"

.SS "double ObjectDB::gripperclose"

.SS "double ObjectDB::height"

.SS "std::size_t ObjectDB::id"

.SS "bool ObjectDB::King"

.SS "std::string ObjectDB::metatype"

.SS "std::string ObjectDB::name"

.SS "std::vector< \fBObjectDB\fP * > ObjectDB::objects\fC [static]\fP"

.SS "Eigen::Affine3d ObjectDB::pose"

.SS "double ObjectDB::radius"

.SS "double ObjectDB::scale"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
