.TH "RCS::PoseTolerance" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::PoseTolerance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.PP
Inherits vector< double >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBPOSITION\fP = 0, \fBORIENTATION\fP = 1, \fBJOINT\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoseTolerance\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBRCS::PoseTolerance::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPOSITION \fP\fP
.TP
\fB\fIORIENTATION \fP\fP
.TP
\fB\fIJOINT \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RCS::PoseTolerance::PoseTolerance ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
