.TH "RCS::CanonCmdType" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonCmdType \- 
.PP
enumeration of Crcl commands\&. Many Crcl commands are wm parameter setting and require no motion component\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCANON_NOOP\fP = 0"
.br
.ti -1c
.RI "static const int \fBCANON_INIT_CANON\fP = 1"
.br
.ti -1c
.RI "static const int \fBCANON_END_CANON\fP = 2"
.br
.ti -1c
.RI "static const int \fBCANON_MOVE_JOINT\fP = 3"
.br
.ti -1c
.RI "static const int \fBCANON_MOVE_TO\fP = 4"
.br
.ti -1c
.RI "static const int \fBCANON_DWELL\fP = 5"
.br
.ti -1c
.RI "static const int \fBCANON_MESSAGE\fP = 6"
.br
.ti -1c
.RI "static const int \fBCANON_MOVE_THRU\fP = 7"
.br
.ti -1c
.RI "static const int \fBCANON_SET_COORDINATED_MOTION\fP = 8"
.br
.ti -1c
.RI "static const int \fBCANON_STOP_MOTION\fP = 9"
.br
.ti -1c
.RI "static const int \fBCANON_SET_GRIPPER\fP = 10"
.br
.ti -1c
.RI "static const int \fBCANON_OPEN_GRIPPER\fP = 11"
.br
.ti -1c
.RI "static const int \fBCANON_CLOSE_GRIPPER\fP = 12"
.br
.ti -1c
.RI "static const int \fBCANON_SET_TOLERANCE\fP = 0"
.br
.ti -1c
.RI "static const int \fBCANON_DRAW_OBJECT\fP = 13"
.br
.ti -1c
.RI "static const int \fBCANON_ERASE_OBJECT\fP = 14"
.br
.ti -1c
.RI "static const int \fBCANON_SET_GRIPPER_POSE\fP = 15"
.br
.ti -1c
.RI "static const int \fBCANON_PICK\fP = 16"
.br
.ti -1c
.RI "static const int \fBCANON_PLACE\fP = 17"
.br
.ti -1c
.RI "static const int \fBCANON_SET_BASE_POSE\fP = 18"
.br
.ti -1c
.RI "static const int \fBCANON_UNKNOWN\fP = -1"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of Crcl commands\&. Many Crcl commands are wm parameter setting and require no motion component\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonCmdType::CANON_CLOSE_GRIPPER = 12\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_DRAW_OBJECT = 13\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_DWELL = 5\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_END_CANON = 2\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_ERASE_OBJECT = 14\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_INIT_CANON = 1\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_MESSAGE = 6\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_MOVE_JOINT = 3\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_MOVE_THRU = 7\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_MOVE_TO = 4\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_NOOP = 0\fC [static]\fP"
uint8 initCanon=1 uint8 endCanon=2 uint8 actuatejoints=3 uint8 moveto=4crclcommand uint8 dwell=5 uint8 message=6 uint8 moveThroughTo=7 uint8 setCoordinatedMotion=8 uint8 stopMotion=9 uint8 setEndEffector=10 uint8 openToolChange=11 uint8 closeToolChanger=12 
.SS "const int RCS::CanonCmdType::CANON_OPEN_GRIPPER = 11\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_PICK = 16\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_PLACE = 17\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_SET_BASE_POSE = 18\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_SET_COORDINATED_MOTION = 8\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_SET_GRIPPER = 10\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_SET_GRIPPER_POSE = 15\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_SET_TOLERANCE = 0\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_STOP_MOTION = 9\fC [static]\fP"

.SS "const int RCS::CanonCmdType::CANON_UNKNOWN = -1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
