.TH "RCS::CanonStopMotionType" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonStopMotionType \- 
.PP
enumeration of stopping motion, e\&.g\&., estop equivalent to immediate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBUNSET\fP = -1"
.br
.ti -1c
.RI "static const int \fBIMMEDIATE\fP = 0"
.br
.ti -1c
.RI "static const int \fBFAST\fP = 1"
.br
.ti -1c
.RI "static const int \fBNORMAL\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
enumeration of stopping motion, e\&.g\&., estop equivalent to immediate\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RCS::CanonStopMotionType::FAST = 1\fC [static]\fP"

.SS "const int RCS::CanonStopMotionType::IMMEDIATE = 0\fC [static]\fP"

.SS "const int RCS::CanonStopMotionType::NORMAL = 2\fC [static]\fP"

.SS "const int RCS::CanonStopMotionType::UNSET = -1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
