.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/NIST/RCSMsgQueueThread.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/NIST/RCSMsgQueueThread.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <boost/signals2/signal\&.hpp>\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/thread/condition\&.hpp>\fP
.br
\fC#include <RCSMsgQueue\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRCS::CMsgQueueThread< T >\fP"
.br
.RI "\fI\fBCMsgQueueThread\fP is a message queued thread\&. It is activated when a message is received\&. 
.br
 Notes: http://stackoverflow.com/questions/768351/complete-example-using-boostsignals-for-c-eventing\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
