.TH "RvizCheckers" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RvizCheckers \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Checkerboard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckers::CheckersGame\fP & \fBGame\fP ()"
.br
.ti -1c
.RI "\fBRvizCheckers\fP (ros::NodeHandle &nh)"
.br
.ti -1c
.RI "bool & \fBReady\fP ()"
.br
.ti -1c
.RI "void \fBcallback\fP (const geometry_msgs::PointStamped::ConstPtr &msg)"
.br
.ti -1c
.RI "Eigen::Affine3d \fBGetPose\fP (int row, int col)"
.br
.ti -1c
.RI "double \fBRowOffset\fP (int row)"
.br
.ti -1c
.RI "double \fBColOffset\fP (int col)"
.br
.ti -1c
.RI "void \fBRvizSetup\fP ()"
.br
.ti -1c
.RI "void \fBSetCheckerColor\fP (\fBCheckers::Move\fP m, rviz_visual_tools::colors color)"
.br
.ti -1c
.RI "bool \fBIsKing\fP (\fBCheckers::Move\fP m)"
.br
.ti -1c
.RI "bool \fBIsAlreadyKing\fP (\fBCheckers::Move\fP m)"
.br
.ti -1c
.RI "void \fBPhysicalMove\fP (\fBInlineRobotCommands\fP &robot, int player, int i, int j, \fBCheckers::Move\fP m)"
.br
.ti -1c
.RI "int \fBPlayer\fP ()"
.br
.ti -1c
.RI "int \fBOpponent\fP ()"
.br
.ti -1c
.RI "int \fBNextPlayer\fP ()"
.br
.ti -1c
.RI "bool \fBCheckersMove\fP (int &player, \fBCheckers::Move\fP &from, \fBCheckers::Move\fP &to)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBxoffset\fP"
.br
.ti -1c
.RI "double \fBrowoffset\fP"
.br
.ti -1c
.RI "double \fByoffset\fP"
.br
.ti -1c
.RI "double \fBoffset\fP"
.br
.ti -1c
.RI "double \fBradius\fP"
.br
.ti -1c
.RI "double \fBheight\fP"
.br
.ti -1c
.RI "\fBCheckers::CheckersGame\fP \fBgame\fP"
.br
.ti -1c
.RI "int \fBcurplayer\fP"
.br
.ti -1c
.RI "ros::Subscriber \fBsub\fP"
.br
.ti -1c
.RI "ros::NodeHandle & \fB_nh\fP"
.br
.ti -1c
.RI "bool \fBbFlag\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBrows\fP = 8"
.br
.ti -1c
.RI "static const int \fBcols\fP = 8"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RvizCheckers::RvizCheckers (ros::NodeHandle &nh)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void RvizCheckers::callback (const geometry_msgs::PointStamped::ConstPtr &msg)\fC [inline]\fP"

.SS "bool RvizCheckers::CheckersMove (int &player, \fBCheckers::Move\fP &from, \fBCheckers::Move\fP &to)\fC [inline]\fP"

.SS "double RvizCheckers::ColOffset (intcol)\fC [inline]\fP"

.SS "\fBCheckers::CheckersGame\fP& RvizCheckers::Game ()\fC [inline]\fP"

.SS "Eigen::Affine3d RvizCheckers::GetPose (introw, intcol)\fC [inline]\fP"

.SS "bool RvizCheckers::IsAlreadyKing (\fBCheckers::Move\fPm)\fC [inline]\fP"

.SS "bool RvizCheckers::IsKing (\fBCheckers::Move\fPm)\fC [inline]\fP"

.SS "int RvizCheckers::NextPlayer ()\fC [inline]\fP"

.SS "int RvizCheckers::Opponent ()\fC [inline]\fP"

.SS "void RvizCheckers::PhysicalMove (\fBInlineRobotCommands\fP &robot, intplayer, inti, intj, \fBCheckers::Move\fPm)\fC [inline]\fP"

.SS "int RvizCheckers::Player ()\fC [inline]\fP"

.SS "bool& RvizCheckers::Ready ()\fC [inline]\fP"

.SS "double RvizCheckers::RowOffset (introw)\fC [inline]\fP"

.SS "void RvizCheckers::RvizSetup ()\fC [inline]\fP"

.SS "void RvizCheckers::SetCheckerColor (\fBCheckers::Move\fPm, rviz_visual_tools::colorscolor)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ros::NodeHandle& RvizCheckers::_nh"

.SS "bool RvizCheckers::bFlag"

.SS "const int RvizCheckers::cols = 8\fC [static]\fP"

.SS "int RvizCheckers::curplayer"

.SS "\fBCheckers::CheckersGame\fP RvizCheckers::game"

.SS "double RvizCheckers::height"

.SS "double RvizCheckers::offset"

.SS "double RvizCheckers::radius"

.SS "double RvizCheckers::rowoffset"

.SS "const int RvizCheckers::rows = 8\fC [static]\fP"

.SS "ros::Subscriber RvizCheckers::sub"

.SS "double RvizCheckers::xoffset"

.SS "double RvizCheckers::yoffset"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
