.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/src/Scene.cpp" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/src/Scene.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Scene\&.h'\fP
.br
\fC#include 'boost/assign\&.hpp'\fP
.br
\fC#include 'BLogging\&.h'\fP
.br
\fC#include 'Conversions\&.h'\fP
.br
\fC#include 'Debug\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBClearScene\fP ()"
.br
.ti -1c
.RI "void \fBInitScene\fP ()"
.br
.ti -1c
.RI "void \fBNewScene\fP ()"
.br
.ti -1c
.RI "void \fBUpdateScene\fP (std::string objname, Eigen::Affine3d pose, rviz_visual_tools::colors color)"
.br
.ti -1c
.RI "void \fBDeleteObject\fP (std::string objname)"
.br
.ti -1c
.RI "void \fBChangeColor\fP (std::string objname, rviz_visual_tools::colors color)"
.br
.ti -1c
.RI "bool \fBDrawObject\fP (\fBObjectDB\fP *obj)"
.br
.ti -1c
.RI "void \fBDrawScene\fP ()"
.br
.ti -1c
.RI "bool \fBpublishCylinder\fP (Eigen::Affine3d pose, rviz_visual_tools::colors color, double height, double radius, size_t &id)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "rviz_visual_tools::RvizVisualToolsPtr \fBvisual_tools\fP"
.br
.ti -1c
.RI "visualization_msgs::Marker \fBtriangle_marker_\fP"
.br
.ti -1c
.RI "visualization_msgs::Marker \fBcylinder_marker_\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ChangeColor (std::stringobjname, rviz_visual_tools::colorscolor)"

.SS "void ClearScene ()"

.SS "void DeleteObject (std::stringobjname)"

.SS "bool DrawObject (\fBObjectDB\fP *obj)"

.SS "void DrawScene ()"

.SS "void InitScene ()"

.SS "void NewScene ()"

.SS "bool publishCylinder (Eigen::Affine3dpose, rviz_visual_tools::colorscolor, doubleheight, doubleradius, size_t &id)"

.SS "void UpdateScene (std::stringobjname, Eigen::Affine3dpose, rviz_visual_tools::colorscolor)"

.SH "Variable Documentation"
.PP 
.SS "visualization_msgs::Marker cylinder_marker_"

.SS "visualization_msgs::Marker triangle_marker_"

.SS "rviz_visual_tools::RvizVisualToolsPtr visual_tools"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
