.TH "/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/StackTrace.h" 3 "Wed Sep 28 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/nistfanuc_ws/src/nist_fanuc/include/nist_fanuc/StackTrace.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <execinfo\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandler\fP (int sig)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void handler (intsig)"
int \fBmain(int argc, char **argv)\fP { signal(SIGSEGV, handler); // install our handler foo(); // this will call foo, bar, and baz\&. baz segfaults\&. } 
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
