gomotion: gomotion::go_interp Class Reference
gomotion::go_interp Class Reference
#include <gointerp.h>
Public Types
typedef go_result(* add_func)(go_real pos)
typedef go_real(* eval_func)(const go_real t)
Public Member Functions
go_result init ()
go_result set_here (go_real here)
go_result calc_coeff_constant (const points *p, coeff *a)
go_result calc_coeff_linear (const points *p, coeff *a)
go_result calc_coeff_cubic_bc (const points *p, coeff *a)
go_result calc_coeff_cubic_pf (const points *p, coeff *a)
go_result calc_coeff_quintic_bc (const points *p, coeff *a)
go_result calc_coeff_quintic_pf (const points *p, coeff *a)
go_result calc_coeff_bc (go_integer order, const points *p, coeff *a)
go_result calc_coeff_pf (go_integer order, const points *p, coeff *a)
go_real eval_constant (go_real t)
go_real eval_linear (go_real t)
go_real eval_cubic (go_real t)
go_real eval_quintic (go_real t)
go_result add_constant (go_real pos)
go_result add_linear (go_real pos)
go_result add_cubic_pv (go_real pos, go_real vel)
go_result add_cubic_pdv (go_real pos)
go_result add_cubic_pf (go_real pos)
go_result add_quintic_pva (go_real pos, go_real vel, go_real acc)
go_result add_quintic_pvda (go_real pos, go_real vel)
go_result add_quintic_pdva (go_real pos)
go_result add_quintic_pf (go_real pos)
Data Fields
coeff a
points p
Detailed Description
Definition at line 54 of file gointerp.h.
Member Typedef Documentation
typedef go_result(* gomotion::go_interp::add_func)(go_real pos)
Definition at line 100 of file gointerp.h.
typedef go_real(* gomotion::go_interp::eval_func)(const go_real t)
Definition at line 101 of file gointerp.h.
Member Function Documentation
go_result gomotion::go_interp::add_constant (go_real pos)
Definition at line 71 of file gointerp.cpp.
References a, calc_coeff_constant(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_cubic_pdv (go_real pos)
Definition at line 251 of file gointerp.cpp.
References a, calc_coeff_cubic_bc(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_cubic_pf (go_real pos)
Definition at line 287 of file gointerp.cpp.
References a, calc_coeff_cubic_pf(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_cubic_pv (go_real pos, go_real vel)
Definition at line 225 of file gointerp.cpp.
References a, calc_coeff_cubic_bc(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_linear (go_real pos)
Definition at line 97 of file gointerp.cpp.
References a, calc_coeff_linear(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_quintic_pdva (go_real pos)
Definition at line 511 of file gointerp.cpp.
References a, calc_coeff_quintic_bc(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_quintic_pf (go_real pos)
Definition at line 553 of file gointerp.cpp.
References a, calc_coeff_quintic_pf(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_quintic_pva (go_real pos, go_real vel, go_real acc)
Definition at line 445 of file gointerp.cpp.
References a, calc_coeff_quintic_bc(), gomotion::points::p, and p.
go_result gomotion::go_interp::add_quintic_pvda (go_real pos, go_real vel)
Definition at line 474 of file gointerp.cpp.
References a, calc_coeff_quintic_bc(), gomotion::points::p, and p.
go_result gomotion::go_interp::calc_coeff_bc (go_integer order, const points * p, coeff * a)
go_result gomotion::go_interp::calc_coeff_constant (const points * p, coeff * a)
Definition at line 63 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_constant().
go_result gomotion::go_interp::calc_coeff_cubic_bc (const points * p, coeff * a)
Definition at line 144 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_cubic_pdv(), and add_cubic_pv().
go_result gomotion::go_interp::calc_coeff_cubic_pf (const points * p, coeff * a)
Definition at line 200 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_cubic_pf().
go_result gomotion::go_interp::calc_coeff_linear (const points * p, coeff * a)
Definition at line 88 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_linear().
go_result gomotion::go_interp::calc_coeff_pf (go_integer order, const points * p, coeff * a)
go_result gomotion::go_interp::calc_coeff_quintic_bc (const points * p, coeff * a)
Definition at line 346 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_quintic_pdva(), add_quintic_pva(), and add_quintic_pvda().
go_result gomotion::go_interp::calc_coeff_quintic_pf (const points * p, coeff * a)
Definition at line 414 of file gointerp.cpp.
References gomotion::coeff::a, GO_RESULT_OK, and gomotion::points::p.
Referenced by add_quintic_pf().
go_real gomotion::go_interp::eval_constant (go_real t)
Definition at line 79 of file gointerp.cpp.
References gomotion::coeff::a, and a.
go_real gomotion::go_interp::eval_cubic (go_real t)
Definition at line 302 of file gointerp.cpp.
References gomotion::coeff::a, and a.
go_real gomotion::go_interp::eval_linear (go_real t)
Definition at line 106 of file gointerp.cpp.
References gomotion::coeff::a, and a.
go_real gomotion::go_interp::eval_quintic (go_real t)
Definition at line 570 of file gointerp.cpp.
References gomotion::coeff::a, and a.
go_result gomotion::go_interp::init ()
Definition at line 35 of file gointerp.cpp.
References gomotion::coeff::a, a, gomotion::COEFF_MAX, GO_RESULT_OK, gomotion::points::p, and p.
go_result gomotion::go_interp::set_here (go_real here)
Definition at line 47 of file gointerp.cpp.
References gomotion::coeff::a, a, gomotion::COEFF_MAX, GO_RESULT_OK, gomotion::points::p, and p.
Field Documentation
coeff gomotion::go_interp::a
Definition at line 56 of file gointerp.h.
Referenced by add_constant(), add_cubic_pdv(), add_cubic_pf(), add_cubic_pv(), add_linear(), add_quintic_pdva(), add_quintic_pf(), add_quintic_pva(), add_quintic_pvda(), eval_constant(), eval_cubic(), eval_linear(), eval_quintic(), init(), and set_here().
points gomotion::go_interp::p
Definition at line 57 of file gointerp.h.
Referenced by add_constant(), add_cubic_pdv(), add_cubic_pf(), add_cubic_pv(), add_linear(), add_quintic_pdva(), add_quintic_pf(), add_quintic_pva(), add_quintic_pvda(), init(), and set_here().
The documentation for this class was generated from the following files:
/usr/local/michalos/nistfanuc_ws/src/gomotion/include/gomotion/gointerp.h
/usr/local/michalos/nistfanuc_ws/src/gomotion/src/gointerp.cpp